In [1]:
import pandas as pd

df = pd.read_csv(
    "../data/Nanchang_WC_Samples_15000.csv"
)

df.head()

,system:index,B11,B12,B2,B3,B4,B8,Class,MNDWI,NDBI,NDVI,lat,lon,.geo
0,0,2141.0,1673.5,513.0,594.5,652.5,1671.0,1,-0.565345,0.123295,0.438347,28.432891,116.472011,"{""geodesic"":false,""type"":""Point"",""coordinates""..."
1,1,1918.0,1791.5,965.5,1190.0,1314.0,1800.0,1,-0.234234,0.031737,0.156069,28.426873,115.964284,"{""geodesic"":false,""type"":""Point"",""coordinates""..."
2,2,1857.0,1297.0,683.0,923.0,937.5,2546.0,1,-0.335971,-0.156484,0.461748,28.548684,115.872566,"{""geodesic"":false,""type"":""Point"",""coordinates""..."
3,3,2108.0,1886.0,792.0,1040.0,1257.0,1819.5,1,-0.339263,0.073456,0.182838,28.643996,115.956558,"{""geodesic"":false,""type"":""Point"",""coordinates""..."
4,4,2500.5,2389.0,1408.0,1669.0,1884.0,2324.0,1,-0.199424,0.036584,0.104563,28.686127,115.855048,"{""geodesic"":false,""type"":""Point"",""coordinates""..."

In [1]:
import pandas as pd

# ==========================
# Load Files
# ==========================

original = pd.read_csv(
    "Wuhan_WC_Samples_15000.csv"
)

manual = pd.read_csv(
    "Wuhan_Top150_Manual.csv"
)

# ==========================
# Backup
# ==========================

corrected = original.copy()

# ==========================
# Apply Corrections
# ==========================

changes = 0

for _, row in manual.iterrows():

    original_id = int(
        row["Original_ID"]
    )

    human_class = int(
        row["Human_Class"]
    )

    old_class = corrected.loc[
        original_id,
        "Class"
    ]

    if old_class != human_class:

        corrected.loc[
            original_id,
            "Class"
        ] = human_class

        changes += 1

print(
    f"Labels changed: {changes}"
)

# ==========================
# Save
# ==========================

corrected.to_csv(
    "Wuhan

SyntaxError: unterminated string literal (detected at line 60) (1058933206.py, line 60)

In [2]:
print(df.shape)

print(df.columns.tolist())

(15000, 14)
['system:index', 'B11', 'B12', 'B2', 'B3', 'B4', 'B8', 'Class', 'MNDWI', 'NDBI', 'NDVI', 'lat', 'lon', '.geo']

In [3]:
df['Class'].value_counts()

Class
1    5000
2    5000
3    5000
Name: count, dtype: int64

In [4]:
df.isnull().sum()

system:index    0
B11             0
B12             0
B2              0
B3              0
B4              0
B8              0
Class           0
MNDWI           0
NDBI            0
NDVI            0
lat             0
lon             0
.geo            0
dtype: int64

In [5]:
print(df.shape)
print(df.columns.tolist())
df['Class'].value_counts()

(15000, 14)
['system:index', 'B11', 'B12', 'B2', 'B3', 'B4', 'B8', 'Class', 'MNDWI', 'NDBI', 'NDVI', 'lat', 'lon', '.geo']

Class
1    5000
2    5000
3    5000
Name: count, dtype: int64

In [9]:
import pandas as pd

from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score

df = pd.read_csv(
    "../data/Nanchang_WC_Samples_15000.csv"
)

features = [
    'B2','B3','B4',
    'B8','B11','B12',
    'NDVI','NDBI','MNDWI'
]

X = df[features]
y = df['Class']

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.3,
    random_state=42,
    stratify=y
)

rf = RandomForestClassifier(
    n_estimators=100,
    random_state=42
)

rf.fit(X_train, y_train)

pred = rf.predict(X_test)

print(
    "OA:",
    accuracy_score(y_test, pred)
)

OA: 0.898

In [10]:
import numpy as np

prob = rf.predict_proba(X_test)

prob[:5]

array([[0.64, 0.36, 0.  ],
       [0.18, 0.82, 0.  ],
       [0.53, 0.47, 0.  ],
       [0.  , 0.03, 0.97],
       [0.  , 0.  , 1.  ]])

In [11]:
sorted_prob = np.sort(
    prob,
    axis=1
)

margin = (
    sorted_prob[:, -1]
    -
    sorted_prob[:, -2]
)

margin[:10]

array([0.28, 0.64, 0.06, 0.94, 1.  , 0.96, 0.32, 0.85, 0.94, 0.98])

In [12]:
hard_idx = np.argsort(margin)

hard_idx[:10]

array([2101, 2580,  831, 2715,  708,  319,  579, 2105, 2125, 2204])

In [13]:
hard_samples = (
    X_test.iloc[hard_idx[:100]]
)

hard_samples.head()

,B2,B3,B4,B8,B11,B12,NDVI,NDBI,MNDWI
9342,894.000000,1365.5,1415.000000,2320.0,1872.0,1282.0,0.242303,-0.106870,-0.156448
10890,504.500000,794.5,636.000000,2422.5,1573.5,1100.5,0.584110,-0.212462,-0.328970
12612,670.000000,999.0,946.000000,1923.0,1572.0,1063.0,0.340537,-0.100429,-0.222870
9999,785.666667,1147.0,1125.333333,2568.0,2403.0,1787.0,0.390614,-0.033193,-0.353803
11843,1587.000000,2014.0,2425.000000,2826.0,3868.0,3461.5,0.076366,0.155662,-0.315199

In [14]:
hard_samples = df.loc[
    X_test.iloc[hard_idx[:100]].index,
    ['lon','lat','Class']
]

hard_samples.head()

              lon        lat  Class
9342   115.980633  29.024342      2
10890  116.428982  28.670586      3
12612  115.906522  28.785840      3
9999   115.987819  28.409356      2
11843  116.098402  28.513560      3

In [16]:
from pathlib import Path

out = Path("../outputs")
out.mkdir(parents=True, exist_ok=True)

hard_samples.to_csv(
    out / "top100_uncertain.csv",
    index=False
)
print("saved:", out.resolve() / "top100_uncertain.csv")

saved: /Users/alex/Projects/gee-project/outputs/top100_uncertain.csv

In [17]:
prob[:5]

margin[:20]

hard_samples.head()

              lon        lat  Class
9342   115.980633  29.024342      2
10890  116.428982  28.670586      3
12612  115.906522  28.785840      3
9999   115.987819  28.409356      2
11843  116.098402  28.513560      3

In [18]:
print("Probability:")
print(prob[:5])

print("\nMargin:")
print(margin[:20])

print("\nHard Samples:")
hard_samples.head()

Probability:
[[0.64 0.36 0.  ]
 [0.18 0.82 0.  ]
 [0.53 0.47 0.  ]
 [0.   0.03 0.97]
 [0.   0.   1.  ]]

Margin:
[0.28 0.64 0.06 0.94 1.   0.96 0.32 0.85 0.94 0.98 0.73 0.96 0.91 0.64
 0.98 0.88 1.   1.   0.89 0.68]

Hard Samples:

              lon        lat  Class
9342   115.980633  29.024342      2
10890  116.428982  28.670586      3
12612  115.906522  28.785840      3
9999   115.987819  28.409356      2
11843  116.098402  28.513560      3

In [19]:
hard_samples = df.loc[
    X_test.iloc[hard_idx[:100]].index,
    ['lon', 'lat', 'Class']
].copy()

hard_samples['margin'] = margin[
    hard_idx[:100]
]

hard_samples.to_csv(
    "../data/top100_uncertain_samples.csv",
    index=False
)

hard_samples.head()

              lon        lat  Class  margin
9342   115.980633  29.024342      2     0.0
10890  116.428982  28.670586      3     0.0
12612  115.906522  28.785840      3     0.0
9999   115.987819  28.409356      2     0.0
11843  116.098402  28.513560      3     0.0

In [20]:
len(hard_samples)

100

In [21]:
hard_samples["margin"].describe()

count    100.000000
mean       0.037000
std        0.021858
min        0.000000
25%        0.020000
50%        0.040000
75%        0.060000
max        0.070000
Name: margin, dtype: float64

In [22]:
hard_samples.to_string()

'              lon        lat  Class  margin\n9342   115.980633  29.024342      2    0.00\n10890  116.428982  28.670586      3    0.00\n12612  115.906522  28.785840      3    0.00\n9999   115.987819  28.409356      2    0.00\n11843  116.098402  28.513560      3    0.00\n5526   115.892957  28.462805      2    0.00\n11210  116.305104  28.714154      3    0.00\n3087   115.541357  28.740475      1    0.01\n11499  115.812468  28.359319      3    0.01\n4196   116.308877  28.272902      1    0.01\n9244   115.945868  28.572400      2    0.01\n4125   116.169369  28.233465      1    0.01\n14568  116.218417  29.063958      3    0.01\n7333   115.899964  28.807758      2    0.01\n11773  116.035520  28.687294      3    0.01\n11824  115.980813  28.842613      3    0.01\n5797   116.236293  28.607254      2    0.01\n9155   115.793244  28.405493      2    0.01\n6553   116.310854  29.053088      2    0.01\n10443  116.023033  29.071683      3    0.02\n6182   116.133796  28.990835      2    0.02\n14253  116.167842  28.600787      3    0.02\n14264  115.902300  28.944572      3    0.02\n1383   115.852264  28.773173      1    0.02\n9516   116.130831  28.300210      2    0.02\n5365   115.963295  28.466578      2    0.02\n14170  116.181047  29.078421      3    0.02\n9215   116.185539  28.476639      2    0.02\n12633  116.287138  29.110670      3    0.02\n4645   115.992401  28.594678      1    0.02\n8567   115.889184  28.749548      2    0.02\n3373   115.897718  28.591803      1    0.02\n8414   116.410836  29.001884      2    0.02\n7988   116.343552  28.963077      2    0.02\n1521   115.784351  28.446726      1    0.02\n4903   116.085197  28.794284      1    0.02\n1708   115.796299  28.563417      1    0.03\n1719   115.779231  28.640312      1    0.03\n14585  116.243660  29.125043      3    0.03\n8432   116.021776  28.422022      2    0.03\n10386  116.099211  28.510596      3    0.03\n7745   115.551148  28.427591      2    0.03\n5215   116.340678  28.937475      2    0.03\n8420   116.261985  28.357882      2    0.03\n14088  115.482158  28.784851      3    0.03\n10729  116.245366  28.738229      3    0.03\n6893   116.128136  28.844410      2    0.03\n14498  116.111607  28.244605      3    0.03\n7618   115.681494  28.904507      2    0.04\n6371   116.096066  28.311978      2    0.04\n14447  116.237282  29.109413      3    0.04\n2563   115.722098  28.670316      1    0.04\n8663   116.249409  28.534940      2    0.04\n7432   116.035700  28.850788      2    0.04\n12564  116.405356  29.005837      3    0.04\n5615   115.893856  28.486701      2    0.04\n4728   116.296031  28.374501      1    0.04\n8214   115.595256  28.794194      2    0.04\n7381   116.311842  28.963077      2    0.04\n8534   115.975692  28.528652      2    0.05\n6951   116.233958  28.192412      2    0.05\n12768  115.579445  28.975384      3    0.05\n7879   116.068578  28.668160      2    0.05\n4379   115.888556  28.732300      1    0.05\n10265  116.010277  28.588570      3    0.05\n3016   116.119692  28.869473      1    0.05\n7511   116.127867  28.720622      2    0.05\n11912  116.118345  28.634384      3    0.05\n10940  115.832321  28.886271      3    0.05\n4146   115.788034  28.614531      1    0.05\n2039   115.811750  28.688372      1    0.05\n3472   115.667211  28.486162      1    0.05\n4591   116.068129  28.353750      1    0.05\n3812   116.002642  28.963347      1    0.06\n7263   116.006594  28.764819      2    0.06\n8322   116.245456  28.478077      2    0.06\n771    115.815612  28.627467      1    0.06\n13540  116.087443  28.489845      3    0.06\n5627   115.980902  28.564045      2    0.06\n10827  116.032466  28.749997      3    0.06\n9407   115.987280  28.442503      2    0.06\n6001   115.838070  28.722778      2    0.06\n4775   115.909307  28.647409      1    0.06\n1369   116.108373  28.520387      1    0.06\n7014   116.402212  28.951309      2    0.06\n661    115.909666  28.817820      1    0.06\n8699   116.218507  28.930289      2    0.06\n11463  116.390894  28.714513      3    0.06\n2814   115.894844  28.535479      1    0.07\n1291   115.727578  28.622526      1    0.07\n14541  115.751563  28.377465      3    0.07\n9085   116.166494  29.098813      2    0.07\n1301   115.550070  28.841445      1    0.07\n4079   116.109092  28.850339      1    0.07\n4007   116.402122  28.313685      1    0.07\n3772   115.745993  28.680108      1    0.07\n9954   115.533901  28.735354      2    0.07\n6124   116.273933  28.992542      2    0.07\n3769   116.105050  28.655314      1    0.07\n1445   116.328461  28.692145      1    0.07'

In [23]:
human_labels = {
  1:2, 2:2, 3:2, 4:2, 5:2,
  6:2, 7:3, 8:1, 9:2, 10:2,
  11:2, 12:1, 13:3, 14:2, 15:2,
  16:3, 17:3, 18:2, 19:3, 20:3,

  21:2,22:2,23:3,24:1,25:2,
  26:2,27:3,28:2,29:3,30:2,
  31:2,32:1,33:3,34:3,35:2,
  36:2,37:1,38:2,39:3,40:2,

  41:2,42:2,43:3,44:2,45:2,
  46:2,47:2,48:2,49:2,50:2,
  51:3,52:1,53:2,54:2,55:3,
  56:2,57:2,58:3,59:3,60:2,

  61:2,62:3,63:1,64:2,65:3,
  66:3,67:3,68:3,69:3,70:1,
  71:2,72:2,73:2,74:3,75:3,
  76:2,77:1,78:3,79:3,80:3,

  81:2,82:2,83:1,84:2,85:3,
  86:2,87:3,88:3,89:1,90:1,
  91:2,92:3,93:3,94:2,95:2,
  96:1,97:2,98:3,99:2,100:2
}

In [24]:
hard_samples = hard_samples.reset_index(drop=True)

hard_samples["PointID"] = range(
    1,
    len(hard_samples)+1
)

hard_samples["WC_Class"] = (
    hard_samples["Class"]
)

hard_samples["Human_Class"] = (
    hard_samples["PointID"]
    .map(human_labels)
)

top100_corrected = hard_samples[
    [
        "PointID",
        "lon",
        "lat",
        "WC_Class",
        "Human_Class",
        "margin"
    ]
]

top100_corrected.head()

   PointID         lon        lat  WC_Class  Human_Class  margin
0        1  115.980633  29.024342         2            2     0.0
1        2  116.428982  28.670586         3            2     0.0
2        3  115.906522  28.785840         3            2     0.0
3        4  115.987819  28.409356         2            2     0.0
4        5  116.098402  28.513560         3            2     0.0

In [25]:
top100_corrected.to_csv(
    "../data/top100_corrected.csv",
    index=False
)

print(
    "Saved top100_corrected.csv"
)

Saved top100_corrected.csv

In [26]:
top100_corrected.shape

(100, 6)

In [27]:
top100_corrected.head()

   PointID         lon        lat  WC_Class  Human_Class  margin
0        1  115.980633  29.024342         2            2     0.0
1        2  116.428982  28.670586         3            2     0.0
2        3  115.906522  28.785840         3            2     0.0
3        4  115.987819  28.409356         2            2     0.0
4        5  116.098402  28.513560         3            2     0.0

In [8]:
import pandas as pd

# ==========================
# Load Files
# ==========================

original = pd.read_csv(
    "../data2/Wuhan/01_original/Wuhan_WC_Samples_15000.csv"
)

manual = pd.read_csv(
    "../data2/Wuhan/04_manual/Wuhan_Top150_Manual.csv"
)

# ==========================
# Apply Corrections
# ==========================

corrected = original.copy()

changes = 0

for _, row in manual.iterrows():

    original_id = int(row["Original_ID"])
    human_class = int(row["Human_Class"])

    old_class = corrected.loc[
        original_id,
        "Class"
    ]

    if old_class != human_class:

        corrected.loc[
            original_id,
            "Class"
        ] = human_class

        changes += 1

print(f"Labels changed: {changes}")

# ==========================
# Save
# ==========================

output_file = (
    "../data2/Wuhan/05_corrected/"
    "Wuhan_Corrected_15000.csv"
)

corrected.to_csv(
    output_file,
    index=False
)

print(f"Saved: {output_file}")

Labels changed: 58
Saved: ../data2/Wuhan/05_corrected/Wuhan_Corrected_15000.csv

In [10]:
import pandas as pd

from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import (
    accuracy_score,
    confusion_matrix,
    classification_report
)

# =====================================
# PATHS
# =====================================

ORIGINAL_FILE = (
    "../data2/Wuhan/01_original/"
    "Wuhan_WC_Samples_15000.csv"
)

CORRECTED_FILE = (
    "../data2/Wuhan/05_corrected/"
    "Wuhan_Corrected_15000.csv"
)

# =====================================
# FEATURES
# =====================================

features = [
    "B2",
    "B3",
    "B4",
    "B8",
    "B11",
    "B12",
    "NDVI",
    "NDBI",
    "MNDWI"
]

# =====================================
# RF FUNCTION
# =====================================

def run_rf(filepath, name):

    print("\n" + "=" * 50)
    print(name)
    print("=" * 50)

    df = pd.read_csv(filepath)

    X = df[features]
    y = df["Class"]

    X_train, X_test, y_train, y_test = train_test_split(
        X,
        y,
        test_size=0.3,
        random_state=42,
        stratify=y
    )

    rf = RandomForestClassifier(
        n_estimators=300,
        random_state=42,
        n_jobs=-1
    )

    rf.fit(X_train, y_train)

    pred = rf.predict(X_test)

    oa = accuracy_score(
        y_test,
        pred
    )

    print(f"OA = {oa:.6f}")

    print("\nConfusion Matrix")
    print(
        confusion_matrix(
            y_test,
            pred
        )
    )

    print("\nClassification Report")
    print(
        classification_report(
            y_test,
            pred,
            digits=4
        )
    )

    return oa

# =====================================
# RUN
# =====================================

oa_original = run_rf(
    ORIGINAL_FILE,
    "ORIGINAL + PIXEL"
)

oa_corrected = run_rf(
    CORRECTED_FILE,
    "CORRECTED + PIXEL"
)

# =====================================
# OA GAIN
# =====================================

gain = oa_corrected - oa_original

print("\n" + "=" * 50)
print("FINAL RESULT")
print("=" * 50)

print(
    f"Original OA   = {oa_original:.6f}"
)

print(
    f"Corrected OA  = {oa_corrected:.6f}"
)

print(
    f"OA Gain       = {gain:.6f}"
)

print(
    f"OA Gain (%)   = {gain*100:.2f}%"
)

==================================================
ORIGINAL + PIXEL
==================================================
OA = 0.899333

Confusion Matrix
[[1354  136   10]
 [ 196 1257   47]
 [  28   36 1436]]

Classification Report
              precision    recall  f1-score   support

           1     0.8580    0.9027    0.8798      1500
           2     0.8796    0.8380    0.8583      1500
           3     0.9618    0.9573    0.9596      1500

    accuracy                         0.8993      4500
   macro avg     0.8998    0.8993    0.8992      4500
weighted avg     0.8998    0.8993    0.8992      4500


==================================================
CORRECTED + PIXEL
==================================================
OA = 0.900444

Confusion Matrix
[[1338  148    6]
 [ 179 1278   50]
 [  22   43 1436]]

Classification Report
              precision    recall  f1-score   support

           1     0.8694    0.8968    0.8829      1492
           2     0.8700    0.8480    0.8589      1507
           3     0.9625    0.9567    0.9596      1501

    accuracy                         0.9004      4500
   macro avg     0.9006    0.9005    0.9004      4500
weighted avg     0.9006    0.9004    0.9004      4500


==================================================
FINAL RESULT
==================================================
Original OA   = 0.899333
Corrected OA  = 0.900444
OA Gain       = 0.001111
OA Gain (%)   = 0.11%

In [12]:
import pandas as pd

from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

df = pd.read_csv(
    "../data2/Wuhan/06_3x3/Wuhan_3x3_Features.csv"
)

features = [
    "B2_mean","B2_stdDev",
    "B3_mean","B3_stdDev",
    "B4_mean","B4_stdDev",
    "B8_mean","B8_stdDev",
    "B11_mean","B11_stdDev",
    "B12_mean","B12_stdDev",
    "NDVI_mean","NDVI_stdDev",
    "NDBI_mean","NDBI_stdDev",
    "MNDWI_mean","MNDWI_stdDev"
]

X = df[features]
y = df["Class"]

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.3,
    random_state=42,
    stratify=y
)

rf = RandomForestClassifier(
    n_estimators=300,
    random_state=42,
    n_jobs=-1
)

rf.fit(X_train, y_train)

pred = rf.predict(X_test)

oa = accuracy_score(y_test, pred)

print("\n===================")
print("ORIGINAL + 3x3")
print("===================")
print(f"OA = {oa:.6f}")

===================
ORIGINAL + 3x3
===================
OA = 0.911778

In [13]:
import pandas as pd

df = pd.read_csv(
    "../data2/Wuhan/06_3x3/Wuhan_3x3_Features.csv"
)

manual = pd.read_csv(
    "../data2/Wuhan/04_manual/Wuhan_Top150_Manual.csv"
)

changes = 0

for _, row in manual.iterrows():

    oid = str(row["Original_ID"])

    human = int(row["Human_Class"])

    mask = df["Original_ID"].astype(str) == oid

    old = df.loc[mask, "Class"].iloc[0]

    if old != human:

        df.loc[mask, "Class"] = human

        changes += 1

print("Labels changed:", changes)

IndexError: single positional indexer is out-of-bounds

In [1]:
import pandas as pd

df = pd.read_csv(
    "../data2/Wuhan/06_3x3/Wuhan_3x3_Features.csv"
)

print(df.columns.tolist())

print(df.head())

['system:index', 'B11_mean', 'B11_stdDev', 'B12_mean', 'B12_stdDev', 'B2_mean', 'B2_stdDev', 'B3_mean', 'B3_stdDev', 'B4_mean', 'B4_stdDev', 'B8_mean', 'B8_stdDev', 'Class', 'MNDWI_mean', 'MNDWI_stdDev', 'NDBI_mean', 'NDBI_stdDev', 'NDVI_mean', 'NDVI_stdDev', 'Original_ID', '.geo']
             system:index    B11_mean  B11_stdDev    B12_mean  B12_stdDev  \
0  000000000000000007e6_0  559.455556  100.911139  394.222222   78.682418
1  000000000000000002e7_0  642.111111  158.608144  523.555556  119.430232
2  00000000000000000c91_0  670.322222   90.340879  510.029987   56.415435
3  0000000000000000046d_0  732.833333  266.651145  612.944444  303.093719
4  00000000000000000a17_0  695.000000  219.353343  607.555556  260.100455

      B2_mean   B2_stdDev     B3_mean   B3_stdDev     B4_mean  ...  \
0  375.387566   60.831448  405.250000   71.599495  333.239815  ...
1  441.666667  133.534016  415.555556  125.150675  372.222222  ...
2  360.483248   26.655617  387.109119   43.982299  360.641943  ...
3  415.500000   77.192400  442.000000  121.879266  431.222222  ...
4  414.444444   37.020869  415.055556   57.819750  391.946296  ...

    B8_stdDev  Class  MNDWI_mean  MNDWI_stdDev  NDBI_mean  NDBI_stdDev  \
0  164.562214      1   -0.158774      0.044914  -0.057950     0.079301
1  171.286634      1   -0.215009      0.097799   0.121201     0.123631
2   88.836049      1   -0.265701      0.048705   0.075126     0.054943
3  186.979714      1   -0.233136      0.066750   0.048544     0.053315
4   93.852658      1   -0.230172      0.102916   0.151493     0.110696

   NDVI_mean  NDVI_stdDev           Original_ID  \
0   0.306399     0.052053  000000000000000007e6
1   0.152278     0.080636  000000000000000002e7
2   0.230592     0.030863  00000000000000000c91
3   0.210217     0.044007  0000000000000000046d
4   0.113062     0.042319  00000000000000000a17

                                     .geo
0  {"type":"MultiPoint","coordinates":[]}
1  {"type":"MultiPoint","coordinates":[]}
2  {"type":"MultiPoint","coordinates":[]}
3  {"type":"MultiPoint","coordinates":[]}
4  {"type":"MultiPoint","coordinates":[]}

[5 rows x 22 columns]

In [5]:
import pandas as pd

df = pd.read_csv("../data2/Wuhan/06_3x3/Wuhan_3x3_Features.csv")

print(df.columns.tolist())

print(
    df[["Original_ID","Class"]].head(10)
)

['Original_ID', 'Original_ID_GEE', 'system:index', 'B11_mean', 'B11_stdDev', 'B12_mean', 'B12_stdDev', 'B2_mean', 'B2_stdDev', 'B3_mean', 'B3_stdDev', 'B4_mean', 'B4_stdDev', 'B8_mean', 'B8_stdDev', 'Class', 'MNDWI_mean', 'MNDWI_stdDev', 'NDBI_mean', 'NDBI_stdDev', 'NDVI_mean', 'NDVI_stdDev', '.geo']
   Original_ID  Class
0         2022      1
1          743      1
2         3217      1
3         1133      1
4         2583      1
5          375      1
6         2947      1
7         3066      1
8         3091      1
9         2534      1

In [6]:
manual = pd.read_csv(
    "../data2/Wuhan/04_manual/Wuhan_Top150_Manual.csv"
)

f3 = pd.read_csv(
    "../data2/Wuhan/06_3x3/Wuhan_3x3_Features.csv"
)

missing = []

for oid in manual["Original_ID"]:

    if oid not in set(f3["Original_ID"]):

        missing.append(oid)

print(
    "Missing:",
    len(missing)
)

print(
    missing[:10]
)

Missing: 0
[]

In [7]:
import pandas as pd

df = pd.read_csv(
    "../data2/Wuhan/06_3x3/Wuhan_3x3_Features.csv"
)

manual = pd.read_csv(
    "../data2/Wuhan/04_manual/Wuhan_Top150_Manual.csv"
)

changes = 0

for _, row in manual.iterrows():

    oid = int(row["Original_ID"])

    human = int(row["Human_Class"])

    mask = df["Original_ID"] == oid

    old = df.loc[
        mask,
        "Class"
    ].iloc[0]

    if old != human:

        df.loc[
            mask,
            "Class"
        ] = human

        changes += 1

print(
    "Labels changed:",
    changes
)

df.to_csv(
    "../data2/Wuhan/06_3x3/Wuhan_3x3_Features_Corrected.csv",
    index=False
)

Labels changed: 58

In [9]:
import pandas as pd

from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

# =================================================
# FILES
# =================================================

FEATURE_FILE = "../data2/Wuhan/06_3x3/Wuhan_3x3_Features.csv"

MANUAL_FILE = (
    "../data2/Wuhan/04_manual/"
    "Wuhan_Top150_Manual.csv"
)

# =================================================
# FEATURES
# =================================================

features = [

    "B2_mean", "B2_stdDev",

    "B3_mean", "B3_stdDev",

    "B4_mean", "B4_stdDev",

    "B8_mean", "B8_stdDev",

    "B11_mean", "B11_stdDev",

    "B12_mean", "B12_stdDev",

    "NDVI_mean", "NDVI_stdDev",

    "NDBI_mean", "NDBI_stdDev",

    "MNDWI_mean", "MNDWI_stdDev"
]

# =================================================
# RF FUNCTION
# =================================================

def run_rf(df, title):

    X = df[features]
    y = df["Class"]

    X_train, X_test, y_train, y_test = train_test_split(
        X,
        y,
        test_size=0.3,
        random_state=42,
        stratify=y
    )

    rf = RandomForestClassifier(
        n_estimators=300,
        random_state=42,
        n_jobs=-1
    )

    rf.fit(X_train, y_train)

    pred = rf.predict(X_test)

    oa = accuracy_score(
        y_test,
        pred
    )

    print("\n" + "=" * 50)
    print(title)
    print("=" * 50)
    print(f"OA = {oa:.6f}")

    return oa

# =================================================
# LOAD ORIGINAL 3x3
# =================================================

df_original = pd.read_csv(
    FEATURE_FILE
)

# =================================================
# ORIGINAL + 3x3
# =================================================

oa_original = run_rf(
    df_original.copy(),
    "ORIGINAL + 3x3"
)

# =================================================
# LOAD MANUAL LABELS
# =================================================

manual = pd.read_csv(
    MANUAL_FILE
)

# =================================================
# APPLY CORRECTIONS
# =================================================

df_corrected = df_original.copy()

changes = 0

for _, row in manual.iterrows():

    oid = int(row["Original_ID"])

    human = int(row["Human_Class"])

    mask = (
        df_corrected["Original_ID"]
        == oid
    )

    if mask.sum() == 0:

        print(
            f"ID NOT FOUND: {oid}"
        )

        continue

    old = df_corrected.loc[
        mask,
        "Class"
    ].iloc[0]

    if old != human:

        df_corrected.loc[
            mask,
            "Class"
        ] = human

        changes += 1

print(
    f"\nLabels changed: {changes}"
)

# =================================================
# SAVE CORRECTED FILE
# =================================================

df_corrected.to_csv(
    "Wuhan_3x3_Features_Corrected.csv",
    index=False
)

# =================================================
# CORRECTED + 3x3
# =================================================

oa_corrected = run_rf(
    df_corrected,
    "CORRECTED + 3x3"
)

# =================================================
# FINAL RESULT
# =================================================

gain = oa_corrected - oa_original

print("\n" + "=" * 50)
print("FINAL RESULT")
print("=" * 50)

print(
    f"Original + 3x3   = {oa_original:.6f}"
)

print(
    f"Corrected + 3x3  = {oa_corrected:.6f}"
)

print(
    f"OA Gain          = {gain:.6f}"
)

print(
    f"OA Gain (%)      = {gain * 100:.2f}%"
)

==================================================
ORIGINAL + 3x3
==================================================
OA = 0.911778

Labels changed: 58

==================================================
CORRECTED + 3x3
==================================================
OA = 0.915333

==================================================
FINAL RESULT
==================================================
Original + 3x3   = 0.911778
Corrected + 3x3  = 0.915333
OA Gain          = 0.003556
OA Gain (%)      = 0.36%

In [11]:
import pandas as pd
import numpy as np

# ==========================================
# FILES
# ==========================================

margin_df = pd.read_csv(
    "../data2/Wuhan/02_margin/Wuhan_MarginScores.csv"
)

f3 = pd.read_csv(
    "../data2/Wuhan/06_3x3/Wuhan_3x3_Features.csv"
)

# ==========================================
# MERGE
# ==========================================

df = margin_df.merge(
    f3[
        [
            "Original_ID",

            "B2_stdDev",
            "B3_stdDev",
            "B4_stdDev",
            "B8_stdDev"
        ]
    ],
    on="Original_ID",
    how="inner"
)

print("Rows:", len(df))

# ==========================================
# Boundary Score
# ==========================================

df["BoundaryScore"] = (

    df["B2_stdDev"] +

    df["B3_stdDev"] +

    df["B4_stdDev"] +

    df["B8_stdDev"]

)

# ==========================================
# Normalize
# ==========================================

df["MarginScore"] = 1 - df["margin"]

df["MarginScore"] = (
    (
        df["MarginScore"]
        -
        df["MarginScore"].min()
    )
    /
    (
        df["MarginScore"].max()
        -
        df["MarginScore"].min()
    )
)

df["BoundaryScore"] = (
    (
        df["BoundaryScore"]
        -
        df["BoundaryScore"].min()
    )
    /
    (
        df["BoundaryScore"].max()
        -
        df["BoundaryScore"].min()
    )
)

# ==========================================
# BAMS Score
# ==========================================

df["BAMS_Score"] = (

    0.7 * df["MarginScore"]

    +

    0.3 * df["BoundaryScore"]

)

# ==========================================
# Top150
# ==========================================

bams150 = (
    df
    .sort_values(
        "BAMS_Score",
        ascending=False
    )
    .head(150)
    .copy()
)

bams150["PointID"] = range(
    1,
    151
)

# ==========================================
# Save
# ==========================================

outfile = (
    "../data2/Wuhan/03_top150/"
    "Wuhan_BAMS150.csv"
)

bams150.to_csv(
    outfile,
    index=False
)

print("\nSaved:")
print(outfile)

print("\nTop20")

print(
    bams150[
        [
            "PointID",
            "Original_ID",
            "margin",
            "BoundaryScore",
            "BAMS_Score"
        ]
    ]
    .head(20)
)

FileNotFoundError: [Errno 2] No such file or directory: '../data2/Wuhan/02_margin/Wuhan_MarginScores.csv'

In [12]:
top150 = pd.read_csv(
    "../data2/Wuhan/03_top150/Wuhan_Top150.csv"
)

print(top150.columns)

Index(['PointID', 'Original_ID', 'lon', 'lat', 'Class', 'margin', 'RF_Pred',
       'prob_1', 'prob_2', 'prob_3'],
      dtype='str')

In [13]:
import pandas as pd
import numpy as np

from sklearn.ensemble import RandomForestClassifier

df = pd.read_csv(
    "../data2/Wuhan/01_original/Wuhan_WC_Samples_15000.csv"
)

features = [
    "B2","B3","B4",
    "B8","B11","B12",
    "NDVI","NDBI","MNDWI"
]

X = df[features]
y = df["Class"]

rf = RandomForestClassifier(
    n_estimators=300,
    random_state=42,
    n_jobs=-1
)

rf.fit(X, y)

probs = rf.predict_proba(X)

sorted_probs = np.sort(
    probs,
    axis=1
)

p1 = sorted_probs[:, -1]
p2 = sorted_probs[:, -2]

df["prob_1"] = p1
df["prob_2"] = p2
df["margin"] = p1 - p2

df["Original_ID"] = range(len(df))

df.to_csv(
    "../data2/Wuhan/02_margin/Wuhan_MarginScores.csv",
    index=False
)

print("Saved MarginScores")

Saved MarginScores

In [14]:
import pandas as pd
import numpy as np

# ==========================================
# FILES
# ==========================================

margin_df = pd.read_csv(
    "../data2/Wuhan/02_margin/Wuhan_MarginScores.csv"
)

f3 = pd.read_csv(
    "../data2/Wuhan/06_3x3/Wuhan_3x3_Features.csv"
)

# ==========================================
# MERGE
# ==========================================

df = margin_df.merge(
    f3[
        [
            "Original_ID",

            "B2_stdDev",
            "B3_stdDev",
            "B4_stdDev",
            "B8_stdDev"
        ]
    ],
    on="Original_ID",
    how="inner"
)

print("Rows:", len(df))

# ==========================================
# Boundary Score
# ==========================================

df["BoundaryScore"] = (

    df["B2_stdDev"] +

    df["B3_stdDev"] +

    df["B4_stdDev"] +

    df["B8_stdDev"]

)

# ==========================================
# Normalize
# ==========================================

df["MarginScore"] = 1 - df["margin"]

df["MarginScore"] = (
    (
        df["MarginScore"]
        -
        df["MarginScore"].min()
    )
    /
    (
        df["MarginScore"].max()
        -
        df["MarginScore"].min()
    )
)

df["BoundaryScore"] = (
    (
        df["BoundaryScore"]
        -
        df["BoundaryScore"].min()
    )
    /
    (
        df["BoundaryScore"].max()
        -
        df["BoundaryScore"].min()
    )
)

# ==========================================
# BAMS Score
# ==========================================

df["BAMS_Score"] = (

    0.7 * df["MarginScore"]

    +

    0.3 * df["BoundaryScore"]

)

# ==========================================
# Top150
# ==========================================

bams150 = (
    df
    .sort_values(
        "BAMS_Score",
        ascending=False
    )
    .head(150)
    .copy()
)

bams150["PointID"] = range(
    1,
    151
)

# ==========================================
# Save
# ==========================================

outfile = (
    "../data2/Wuhan/03_top150/"
    "Wuhan_BAMS150.csv"
)

bams150.to_csv(
    outfile,
    index=False
)

print("\nSaved:")
print(outfile)

print("\nTop20")

print(
    bams150[
        [
            "PointID",
            "Original_ID",
            "margin",
            "BoundaryScore",
            "BAMS_Score"
        ]
    ]
    .head(20)
)

Rows: 15000

Saved:
../data2/Wuhan/03_top150/Wuhan_BAMS150.csv

Top20
       PointID  Original_ID    margin  BoundaryScore  BAMS_Score
7586         1         7586  0.143333       0.156382    0.744201
445          2          445  0.140000       0.126177    0.737853
6212         3         6212  0.213333       0.302380    0.731024
7342         4         7342  0.223333       0.328021    0.730577
9546         5         9546  0.226667       0.320331    0.725557
9434         6         9434  0.153333       0.121235    0.725518
6412         7         6412  0.270000       0.413239    0.718158
14813        8        14813  0.243333       0.323351    0.712897
7159         9         7159  0.223333       0.231236    0.701541
9666        10         9666  0.243333       0.264600    0.695271
5054        11         5054  0.240000       0.249365    0.693414
9192        12         9192  0.300000       0.410518    0.692923
9847        13         9847  0.360000       0.564321    0.690226
5497        14         5497  0.160000       0.009745    0.686644
5133        15         5133  0.180000       0.063336    0.686443
8611        16         8611  0.193333       0.094782    0.685024
12963       17        12963  0.200000       0.109693    0.684071
1148        18         1148  0.260000       0.269166    0.683075
9165        19         9165  0.276667       0.297951    0.678145
8589        20         8589  0.206667       0.102189    0.676393

In [15]:
manual = bams150[
    [
        "PointID",
        "Original_ID"
    ]
].copy()

manual["Human_Class"] = ""
manual["Scene"] = ""
manual["Notes"] = ""

manual.to_csv(
    "../data2/Wuhan/04_manual/Wuhan_BAMS150_Manual.csv",
    index=False
)

print(
    "Manual file created."
)

Manual file created.

In [16]:
import pandas as pd

orig = pd.read_csv(
    "../data2/Wuhan/01_original/Wuhan_WC_Samples_15000.csv"
)

bams = pd.read_csv(
    "../data2/Wuhan/04_manual/Wuhan_BAMS150_Manual.csv"
)

print("Original samples:", len(orig))
print("BAMS samples:", len(bams))

print(
    "Unique Original_ID:",
    bams["Original_ID"].nunique()
)

Original samples: 15000
BAMS samples: 150
Unique Original_ID: 150

In [17]:
margin150 = pd.read_csv(
    "../data2/Wuhan/03_top150/Wuhan_Top150.csv"
)

bams150 = pd.read_csv(
    "../data2/Wuhan/04_manual/Wuhan_BAMS150_Manual.csv"
)

margin_ids = set(
    margin150["Original_ID"]
)

bams_ids = set(
    bams150["Original_ID"]
)

overlap = margin_ids & bams_ids

print(
    "Overlap:",
    len(overlap)
)

print(
    "Overlap Rate:",
    len(overlap) / 150
)

Overlap: 0
Overlap Rate: 0.0

In [18]:
print(len(df))
print(df["Original_ID"].nunique())

15000
15000

In [19]:
margin150 = pd.read_csv(
    "../data2/Wuhan/03_top150/Wuhan_Top150.csv"
)

bams150 = pd.read_csv(
    "../data2/Wuhan/03_top150/Wuhan_BAMS150.csv"
)

print("Margin Top10")
print(
    margin150[
        ["Original_ID","margin"]
    ].head(10)
)

print("\nBAMS Top10")
print(
    bams150[
        ["Original_ID","margin","BAMS_Score"]
    ].head(10)
)

Margin Top10
   Original_ID  margin
0         9045     0.0
1         6215     0.0
2         4063     0.0
3         5950     0.0
4          762     0.0
5         2738     0.0
6         3315     0.0
7         9260     0.0
8         2368     0.0
9         5387     0.0

BAMS Top10
   Original_ID    margin  BAMS_Score
0         7586  0.143333    0.744201
1          445  0.140000    0.737853
2         6212  0.213333    0.731024
3         7342  0.223333    0.730577
4         9546  0.226667    0.725557
5         9434  0.153333    0.725518
6         6412  0.270000    0.718158
7        14813  0.243333    0.712897
8         7159  0.223333    0.701541
9         9666  0.243333    0.695271

In [20]:
print(
    len(
        set(margin150["Original_ID"])
        &
        set(bams150["Original_ID"])
    )
)

0

In [21]:
print(
    bams150["margin"].describe()
)

print(
    margin150["margin"].describe()
)

count    150.000000
mean       0.280156
std        0.045769
min        0.140000
25%        0.250833
50%        0.286667
75%        0.313333
max        0.370000
Name: margin, dtype: float64
count    150.000000
mean       0.040867
std        0.025275
min        0.000000
25%        0.020000
50%        0.040000
75%        0.060000
max        0.080000
Name: margin, dtype: float64

In [22]:
import pandas as pd

# ==========================================
# FILES
# ==========================================

MARGIN_FILE = (
    "../data2/Wuhan/02_margin/"
    "Wuhan_MarginScores.csv"
)

FEATURE_FILE = (
    "../data2/Wuhan/06_3x3/"
    "Wuhan_3x3_Features.csv"
)

# ==========================================
# LOAD
# ==========================================

margin_df = pd.read_csv(
    MARGIN_FILE
)

f3 = pd.read_csv(
    FEATURE_FILE
)

# ==========================================
# MERGE
# ==========================================

df = margin_df.merge(
    f3[
        [
            "Original_ID",
            "B2_stdDev",
            "B3_stdDev",
            "B4_stdDev",
            "B8_stdDev"
        ]
    ],
    on="Original_ID",
    how="inner"
)

print("Rows:", len(df))
print(
    "Unique IDs:",
    df["Original_ID"].nunique()
)

# ==========================================
# Boundary Score
# ==========================================

df["BoundaryScore"] = (

    df["B2_stdDev"]

    + df["B3_stdDev"]

    + df["B4_stdDev"]

    + df["B8_stdDev"]

)

# ==========================================
# STEP 1
# Most Uncertain 1000
# ==========================================

candidate = (
    df
    .sort_values(
        "margin",
        ascending=True
    )
    .head(1000)
    .copy()
)

print(
    "\nCandidate Samples:",
    len(candidate)
)

# ==========================================
# STEP 2
# Highest Boundary Score
# ==========================================

bams150 = (
    candidate
    .sort_values(
        "BoundaryScore",
        ascending=False
    )
    .head(150)
    .copy()
)

# ==========================================
# PointID
# ==========================================

bams150 = bams150.reset_index(
    drop=True
)

bams150["PointID"] = range(
    1,
    151
)

# ==========================================
# Column Order
# ==========================================

cols = [

    "PointID",

    "Original_ID",

    "Class",

    "margin",

    "BoundaryScore",

    "lon",

    "lat"

]

cols = [
    c for c in cols
    if c in bams150.columns
]

bams150 = bams150[cols]

# ==========================================
# SAVE
# ==========================================

out_file = (
    "../data2/Wuhan/03_top150/"
    "Wuhan_BAMS150.csv"
)

bams150.to_csv(
    out_file,
    index=False
)

print(
    "\nSaved:",
    out_file
)

# ==========================================
# MANUAL TEMPLATE
# ==========================================

manual = bams150[
    [
        "PointID",
        "Original_ID"
    ]
].copy()

manual["Human_Class"] = ""
manual["Scene"] = ""
manual["Notes"] = ""

manual_file = (
    "../data2/Wuhan/04_manual/"
    "Wuhan_BAMS150_Manual.csv"
)

manual.to_csv(
    manual_file,
    index=False
)

print(
    "Saved:",
    manual_file
)

# ==========================================
# CHECK OVERLAP
# ==========================================

margin150 = pd.read_csv(
    "../data2/Wuhan/03_top150/Wuhan_Top150.csv"
)

overlap = len(

    set(
        margin150["Original_ID"]
    )

    &

    set(
        bams150["Original_ID"]
    )
)

print("\n==================")
print("OVERLAP CHECK")
print("==================")

print(
    "Overlap:",
    overlap
)

print(
    "Overlap Rate:",
    overlap / 150
)

# ==========================================
# DISPLAY TOP20
# ==========================================

print("\nTop20 BAMS Samples")

print(
    bams150.head(20)
)

Rows: 15000
Unique IDs: 15000

Candidate Samples: 1000

Saved: ../data2/Wuhan/03_top150/Wuhan_BAMS150.csv
Saved: ../data2/Wuhan/04_manual/Wuhan_BAMS150_Manual.csv

==================
OVERLAP CHECK
==================
Overlap: 3
Overlap Rate: 0.02

Top20 BAMS Samples
    PointID  Original_ID  Class    margin  BoundaryScore         lon  \
0         1         9847      2  0.360000    2675.152651  114.371032
1         2         5089      2  0.543333    2646.726533  114.282997
2         3         9948      2  0.526667    2432.424638  114.768177
3         4         5474      2  0.353333    2163.360179  114.310216
4         5         9953      2  0.493333    2025.749180  113.936696
5         6         6412      2  0.270000    1960.914449  114.477033
6         7         9192      2  0.300000    1948.053104  114.663793
7         8         4001      1  0.343333    1876.543697  114.401395
8         9        12096      3  0.313333    1779.483723  114.522488
9        10         9912      2  0.560000    1747.416478  114.619955
10       11         1409      1  0.473333    1722.045285  113.901482
11       12         7604      2  0.516667    1703.263045  114.510091
12       13         9476      2  0.543333    1638.638784  114.436339
13       14         5282      2  0.336667    1616.555895  114.062730
14       15         4708      1  0.506667    1600.960639  114.426368
15       16         7342      2  0.223333    1558.047216  114.283626
16       17        14813      3  0.243333    1535.969959  114.287848
17       18         5800      2  0.450000    1531.903799  114.598036
18       19         9546      2  0.226667    1521.694675  113.983409
19       20         6321      2  0.526667    1518.400811  114.913255

          lat
0   30.860139
1   30.467306
2   30.681105
3   30.706527
4   30.359778
5   30.350974
6   30.603581
7   30.452304
8   30.990305
9   30.746143
10  30.458503
11  30.490123
12  31.161883
13  30.415473
14  30.483745
15  30.711828
16  30.569624
17  30.754497
18  30.693771
19  31.000636

In [23]:
print(
    bams150["BoundaryScore"].describe()
)

print(
    candidate["BoundaryScore"].describe()
)

count     150.000000
mean     1199.746814
std       326.732106
min       904.585168
25%       973.570337
50%      1099.903024
75%      1299.965023
max      2675.152651
Name: BoundaryScore, dtype: float64
count    1000.000000
mean      592.551236
std       349.722410
min        22.014868
25%       361.882114
50%       556.128918
75%       759.821533
max      2675.152651
Name: BoundaryScore, dtype: float64

In [24]:
bams30 = bams150.head(30)

bams30.to_csv(
    "../data2/Wuhan/03_top150/Wuhan_BAMS30.csv",
    index=False
)

In [25]:
import pandas as pd

# ==========================================
# Load
# ==========================================

margin_df = pd.read_csv(
    "../data2/Wuhan/02_margin/Wuhan_MarginScores.csv"
)

f3 = pd.read_csv(
    "../data2/Wuhan/06_3x3/Wuhan_3x3_Features.csv"
)

# ==========================================
# Merge
# ==========================================

df = margin_df.merge(
    f3[
        [
            "Original_ID",
            "B2_stdDev",
            "B3_stdDev",
            "B4_stdDev",
            "B8_stdDev"
        ]
    ],
    on="Original_ID",
    how="inner"
)

# ==========================================
# Boundary Score
# ==========================================

df["BoundaryScore"] = (

    df["B2_stdDev"]
    + df["B3_stdDev"]
    + df["B4_stdDev"]
    + df["B8_stdDev"]

)

# ==========================================
# Candidate
# ==========================================

candidate = (
    df
    .sort_values(
        "margin",
        ascending=True
    )
    .head(1000)
    .copy()
)

# ==========================================
# BAMS
# ==========================================

bams150 = (
    candidate
    .sort_values(
        "BoundaryScore",
        ascending=False
    )
    .head(150)
    .copy()
)

bams150 = bams150.reset_index(
    drop=True
)

bams150["PointID"] = range(
    1,
    151
)

bams150["Method"] = "BAMS150"

# ==========================================
# Same schema as Margin150
# ==========================================

keep_cols = [

    "PointID",

    "Original_ID",

    "lon",
    "lat",

    "Class",

    "margin",

    "BoundaryScore",

    "RF_Pred",

    "prob_1",
    "prob_2",
    "prob_3",

    "Method"
]

keep_cols = [
    c
    for c in keep_cols
    if c in bams150.columns
]

bams150 = bams150[
    keep_cols
]

# ==========================================
# Save
# ==========================================

bams150.to_csv(

    "../data2/Wuhan/03_top150/Wuhan_BAMS150.csv",

    index=False

)

print(
    bams150.head()
)

print(
    bams150.columns.tolist()
)

   PointID  Original_ID         lon        lat  Class    margin  \
0        1         9847  114.371032  30.860139      2  0.360000
1        2         5089  114.282997  30.467306      2  0.543333
2        3         9948  114.768177  30.681105      2  0.526667
3        4         5474  114.310216  30.706527      2  0.353333
4        5         9953  113.936696  30.359778      2  0.493333

   BoundaryScore    prob_1    prob_2   Method
0    2675.152651  0.670000  0.310000  BAMS150
1    2646.726533  0.770000  0.226667  BAMS150
2    2432.424638  0.746667  0.220000  BAMS150
3    2163.360179  0.673333  0.320000  BAMS150
4    2025.749180  0.746667  0.253333  BAMS150
['PointID', 'Original_ID', 'lon', 'lat', 'Class', 'margin', 'BoundaryScore', 'prob_1', 'prob_2', 'Method']

In [26]:
import pandas as pd

bams = pd.read_csv(
    "../data2/Wuhan/03_top150/Wuhan_BAMS150.csv"
)

manual = pd.read_csv(
    "../data2/Wuhan/04_manual/Wuhan_BAMS150_Manual.csv"
)

df = bams.merge(
    manual[
        ["Original_ID", "Human_Class", "Scene"]
    ],
    on="Original_ID"
)

df["Human_Class"] = (
    pd.to_numeric(
        df["Human_Class"],
        errors="coerce"
    )
)

correct = (
    df["Class"] == df["Human_Class"]
).sum()

total = len(df)

acc = correct / total

print(f"Correct = {correct}")
print(f"Wrong   = {total-correct}")
print(f"Accuracy = {acc:.4f}")
print(f"Error Rate = {1-acc:.4f}")

Correct = 63
Wrong   = 87
Accuracy = 0.4200
Error Rate = 0.5800

In [27]:
import pandas as pd

# =====================================
# FILES
# =====================================

ORIGINAL_FILE = (
    "../data2/Wuhan/01_original/"
    "Wuhan_WC_Samples_15000.csv"
)

MANUAL_FILE = (
    "../data2/Wuhan/04_manual/"
    "Wuhan_BAMS150_Manual.csv"
)

OUTPUT_FILE = (
    "../data2/Wuhan/05_corrected/"
    "Wuhan_BAMS_Corrected_15000.csv"
)

# =====================================
# LOAD
# =====================================

df = pd.read_csv(
    ORIGINAL_FILE
)

manual = pd.read_csv(
    MANUAL_FILE
)

# =====================================
# APPLY CORRECTIONS
# =====================================

changes = 0

for _, row in manual.iterrows():

    oid = int(row["Original_ID"])

    human = int(row["Human_Class"])

    old_class = df.loc[
        oid,
        "Class"
    ]

    if old_class != human:

        df.loc[
            oid,
            "Class"
        ] = human

        changes += 1

# =====================================
# SAVE
# =====================================

df.to_csv(
    OUTPUT_FILE,
    index=False
)

# =====================================
# REPORT
# =====================================

print("=" * 50)
print("BAMS CORRECTION")
print("=" * 50)

print(
    f"Labels changed: {changes}"
)

print(
    f"Saved: {OUTPUT_FILE}"
)

==================================================
BAMS CORRECTION
==================================================
Labels changed: 87
Saved: ../data2/Wuhan/05_corrected/Wuhan_BAMS_Corrected_15000.csv

In [28]:
import pandas as pd

from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import (
    accuracy_score,
    confusion_matrix,
    classification_report
)

# =====================================
# FILE
# =====================================

FILE = (
    "../data2/Wuhan/05_corrected/"
    "Wuhan_BAMS_Corrected_15000.csv"
)

# =====================================
# FEATURES
# =====================================

features = [
    "B2",
    "B3",
    "B4",
    "B8",
    "B11",
    "B12",
    "NDVI",
    "NDBI",
    "MNDWI"
]

# =====================================
# LOAD
# =====================================

df = pd.read_csv(FILE)

X = df[features]
y = df["Class"]

# =====================================
# TRAIN TEST SPLIT
# =====================================

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.3,
    random_state=42,
    stratify=y
)

# =====================================
# RANDOM FOREST
# =====================================

rf = RandomForestClassifier(
    n_estimators=300,
    random_state=42,
    n_jobs=-1
)

rf.fit(X_train, y_train)

pred = rf.predict(X_test)

# =====================================
# RESULTS
# =====================================

oa = accuracy_score(
    y_test,
    pred
)

print("\n" + "=" * 50)
print("BAMS CORRECTED + PIXEL")
print("=" * 50)

print(f"OA = {oa:.6f}")

print("\nConfusion Matrix")
print(
    confusion_matrix(
        y_test,
        pred
    )
)

print("\nClassification Report")
print(
    classification_report(
        y_test,
        pred,
        digits=4
    )
)

==================================================
BAMS CORRECTED + PIXEL
==================================================
OA = 0.909111

Confusion Matrix
[[1383  110    9]
 [ 166 1273   60]
 [  26   38 1435]]

Classification Report
              precision    recall  f1-score   support

           1     0.8781    0.9208    0.8989      1502
           2     0.8958    0.8492    0.8719      1499
           3     0.9541    0.9573    0.9557      1499

    accuracy                         0.9091      4500
   macro avg     0.9094    0.9091    0.9089      4500
weighted avg     0.9093    0.9091    0.9088      4500

In [31]:
import pandas as pd

from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import (
    accuracy_score,
    confusion_matrix,
    classification_report
)

# =====================================
# FILES
# =====================================

FEATURE_FILE = (
    "../data2/Wuhan/06_3x3/"
    "Wuhan_3x3_Features.csv"
)

MANUAL_FILE = (
    "../data2/Wuhan/04_manual/"
    "Wuhan_BAMS150_Manual.csv"
)

# =====================================
# LOAD
# =====================================

df = pd.read_csv(FEATURE_FILE)

manual = pd.read_csv(MANUAL_FILE)

# =====================================
# APPLY BAMS CORRECTIONS
# =====================================

changes = 0

for _, row in manual.iterrows():

    oid = int(row["Original_ID"])

    human = int(row["Human_Class"])

    mask = (
        df["Original_ID"] == oid
    )

    if mask.sum() == 0:

        print(
            f"ID NOT FOUND: {oid}"
        )

        continue

    old = df.loc[
        mask,
        "Class"
    ].iloc[0]

    if old != human:

        df.loc[
            mask,
            "Class"
        ] = human

        changes += 1

print(
    f"\nLabels changed: {changes}"
)

# =====================================
# SAVE CORRECTED 3x3
# =====================================

df.to_csv(
    "../data2/Wuhan/06_3x3/Wuhan_BAMS_Corrected_3x3.csv",
    index=False
)

# =====================================
# FEATURES
# =====================================

features = [

    "B2_mean", "B2_stdDev",

    "B3_mean", "B3_stdDev",

    "B4_mean", "B4_stdDev",

    "B8_mean", "B8_stdDev",

    "B11_mean", "B11_stdDev",

    "B12_mean", "B12_stdDev",

    "NDVI_mean", "NDVI_stdDev",

    "NDBI_mean", "NDBI_stdDev",

    "MNDWI_mean", "MNDWI_stdDev"
]

# =====================================
# DATA
# =====================================

X = df[features]
y = df["Class"]

# =====================================
# TRAIN TEST SPLIT
# =====================================

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.3,
    random_state=42,
    stratify=y
)

# =====================================
# RF
# =====================================

rf = RandomForestClassifier(
    n_estimators=300,
    random_state=42,
    n_jobs=-1
)

rf.fit(
    X_train,
    y_train
)

pred = rf.predict(
    X_test
)

# =====================================
# RESULTS
# =====================================

oa = accuracy_score(
    y_test,
    pred
)

print("\n" + "="*50)
print("BAMS CORRECTED + 3x3")
print("="*50)

print(
    f"OA = {oa:.6f}"
)

print("\nConfusion Matrix")

print(
    confusion_matrix(
        y_test,
        pred
    )
)

print("\nClassification Report")

print(
    classification_report(
        y_test,
        pred,
        digits=4
    )
)

Labels changed: 87

==================================================
BAMS CORRECTED + 3x3
==================================================
OA = 0.916889

Confusion Matrix
[[1402   97    3]
 [ 160 1276   63]
 [  16   35 1448]]

Classification Report
              precision    recall  f1-score   support

           1     0.8885    0.9334    0.9104      1502
           2     0.9062    0.8512    0.8779      1499
           3     0.9564    0.9660    0.9612      1499

    accuracy                         0.9169      4500
   macro avg     0.9170    0.9169    0.9165      4500
weighted avg     0.9170    0.9169    0.9165      4500

In [32]:
import pandas as pd

ORIGINAL_FILE = (
    "../data2/Hefei/01_original/"
    "Hefei_WC_Samples_15000.csv"
)

MANUAL_FILE = (
    "../data2/Hefei/04_manual/"
    "Hefei_Top150_Manual.csv"
)

OUTPUT_FILE = (
    "../data2/Hefei/05_corrected/"
    "Hefei_Corrected_15000.csv"
)

df = pd.read_csv(ORIGINAL_FILE)

manual = pd.read_csv(MANUAL_FILE)

changes = 0

for _, row in manual.iterrows():

    oid = int(row["Original_ID"])

    human = int(row["Human_Class"])

    mask = df["Original_ID"] == oid

    old_class = df.loc[
        mask,
        "Class"
    ].iloc[0]

    if old_class != human:

        df.loc[
            mask,
            "Class"
        ] = human

        changes += 1

df.to_csv(
    OUTPUT_FILE,
    index=False
)

print(
    f"Labels changed: {changes}"
)

print(
    f"Saved: {OUTPUT_FILE}"
)

Labels changed: 59
Saved: ../data2/Hefei/05_corrected/Hefei_Corrected_15000.csv

In [ ]:
import pandas as pd

from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score


FILE = (
    "../data2/Hefei/05_corrected/"
    "Hefei_Corrected_15000.csv"
)
features = [
    "B2",
    "B3",
    "B4",
    "B8",
    "B11",
    "B12",
    "NDVI",
    "NDBI",
    "MNDWI"
]

df = pd.read_csv(FILE)

X = df[features]
y = df["Class"]

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.3,
    random_state=42,
    stratify=y
)

rf = RandomForestClassifier(
    n_estimators=300,
    random_state=42,
    n_jobs=-1
)

rf.fit(X_train, y_train)

pred = rf.predict(X_test)

oa = accuracy_score(
    y_test,
    pred
)

print(
    f"Original + Pixel OA = {oa:.6f}"
)

Original + Pixel OA = 0.916222

In [ ]:
import pandas as pd

from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score


FILE = (
    "../data2/Hefei/05_corrected/"
    "Hefei_Corrected_15000.csv"
)
features = [
    "B2",
    "B3",
    "B4",
    "B8",
    "B11",
    "B12",
    "NDVI",
    "NDBI",
    "MNDWI"
]

df = pd.read_csv(FILE)

X = df[features]
y = df["Class"]

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.3,
    random_state=42,
    stratify=y
)

rf = RandomForestClassifier(
    n_estimators=300,
    random_state=42,
    n_jobs=-1
)

rf.fit(X_train, y_train)

pred = rf.predict(X_test)

oa = accuracy_score(
    y_test,
    pred
)

print(
    f"Correct + Pixel OA = {oa:.6f}"
)

Original + Pixel OA = 0.920667

In [35]:
import pandas as pd

from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

FILE = (
    "../data2/Hefei/06_3x3/"
    "Hefei_3x3_Features.csv"
)

features = [

    "B2_mean","B2_stdDev",
    "B3_mean","B3_stdDev",
    "B4_mean","B4_stdDev",
    "B8_mean","B8_stdDev",

    "B11_mean","B11_stdDev",
    "B12_mean","B12_stdDev",

    "NDVI_mean","NDVI_stdDev",
    "NDBI_mean","NDBI_stdDev",
    "MNDWI_mean","MNDWI_stdDev"
]

df = pd.read_csv(FILE)

X = df[features]
y = df["Class"]

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.3,
    random_state=42,
    stratify=y
)

rf = RandomForestClassifier(
    n_estimators=300,
    random_state=42,
    n_jobs=-1
)

rf.fit(X_train, y_train)

pred = rf.predict(X_test)

oa = accuracy_score(
    y_test,
    pred
)

print(
    f"Original + 3x3 OA = {oa:.6f}"
)

Original + 3x3 OA = 0.933556

In [ ]:
import pandas as pd

from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import (
    accuracy_score,
    confusion_matrix,
    classification_report
)

# =====================================
# FILES
# =====================================

FEATURE_FILE = (
    "../data2/Hefei/06_3x3/"
    "Hefei_3x3_Features.csv"
)

MANUAL_FILE = (
    "../data2/Hefei/04_manual/"
    "Hefei_Top150_Manual.csv"
)

CORRECTED_FILE = (
    "../data2/Hefei/06_3x3/"
    "Hefei_3x3_Features_Corrected.csv"
)

# =====================================
# LOAD
# =====================================

df = pd.read_csv(FEATURE_FILE)

manual = pd.read_csv(MANUAL_FILE)

# =====================================
# APPLY LABEL CORRECTIONS
# =====================================

changes = 0

for _, row in manual.iterrows():

    oid = int(row["Original_ID"])

    human = int(row["Human_Class"])

    mask = (
        df["Original_ID"] == oid
    )

    if mask.sum() == 0:
        print(f"ID NOT FOUND: {oid}")
        continue

    old_class = df.loc[
        mask,
        "Class"
    ].iloc[0]

    if old_class != human:

        df.loc[
            mask,
            "Class"
        ] = human

        changes += 1

print(
    f"\nLabels changed: {changes}"
)

# =====================================
# SAVE CORRECTED FILE
# =====================================

df.to_csv(
    CORRECTED_FILE,
    index=False
)

print(
    f"Saved: {CORRECTED_FILE}"
)

# =====================================
# FEATURES
# =====================================

features = [

    "B2_mean", "B2_stdDev",

    "B3_mean", "B3_stdDev",

    "B4_mean", "B4_stdDev",

    "B8_mean", "B8_stdDev",

    "B11_mean", "B11_stdDev",

    "B12_mean", "B12_stdDev",

    "NDVI_mean", "NDVI_stdDev",

    "NDBI_mean", "NDBI_stdDev",

    "MNDWI_mean", "MNDWI_stdDev"
]

# =====================================
# DATA
# =====================================

X = df[features]
y = df["Class"]

# =====================================
# TRAIN TEST SPLIT
# =====================================

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.3,
    random_state=42,
    stratify=y
)

# =====================================
# RANDOM FOREST
# =====================================

rf = RandomForestClassifier(
    n_estimators=300,
    random_state=42,
    n_jobs=-1
)

rf.fit(
    X_train,
    y_train
)

pred = rf.predict(
    X_test
)

# =====================================
# RESULTS
# =====================================

oa = accuracy_score(
    y_test,
    pred
)

print("\n" + "=" * 50)
print("HEFEI MARGIN CORRECTED + 3x3")
print("=" * 50)

print(
    f"OA = {oa:.6f}"
)

print("\nConfusion Matrix")

print(
    confusion_matrix(
        y_test,
        pred
    )
)

print("\nClassification Report")

print(
    classification_report(
        y_test,
        pred,
        digits=4
    )
)

Labels changed: 59

In [37]:
import pandas as pd

from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import (
    accuracy_score,
    confusion_matrix,
    classification_report
)

# =====================================
# FILES
# =====================================

FEATURE_FILE = (
    "../data2/Hefei/06_3x3/"
    "Hefei_3x3_Features.csv"
)

MANUAL_FILE = (
    "../data2/Hefei/04_manual/"
    "Hefei_Top150_Manual.csv"
)

CORRECTED_FILE = (
    "../data2/Hefei/06_3x3/"
    "Hefei_3x3_Features_Corrected.csv"
)

# =====================================
# LOAD
# =====================================

df = pd.read_csv(FEATURE_FILE)

manual = pd.read_csv(MANUAL_FILE)

# =====================================
# APPLY LABEL CORRECTIONS
# =====================================

changes = 0

for _, row in manual.iterrows():

    oid = int(row["Original_ID"])

    human = int(row["Human_Class"])

    mask = (
        df["Original_ID"] == oid
    )

    if mask.sum() == 0:
        print(f"ID NOT FOUND: {oid}")
        continue

    old_class = df.loc[
        mask,
        "Class"
    ].iloc[0]

    if old_class != human:

        df.loc[
            mask,
            "Class"
        ] = human

        changes += 1

print(
    f"\nLabels changed: {changes}"
)

# =====================================
# SAVE CORRECTED FILE
# =====================================

df.to_csv(
    CORRECTED_FILE,
    index=False
)

print(
    f"Saved: {CORRECTED_FILE}"
)

# =====================================
# FEATURES
# =====================================

features = [

    "B2_mean", "B2_stdDev",

    "B3_mean", "B3_stdDev",

    "B4_mean", "B4_stdDev",

    "B8_mean", "B8_stdDev",

    "B11_mean", "B11_stdDev",

    "B12_mean", "B12_stdDev",

    "NDVI_mean", "NDVI_stdDev",

    "NDBI_mean", "NDBI_stdDev",

    "MNDWI_mean", "MNDWI_stdDev"
]

# =====================================
# DATA
# =====================================

X = df[features]
y = df["Class"]

# =====================================
# TRAIN TEST SPLIT
# =====================================

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.3,
    random_state=42,
    stratify=y
)

# =====================================
# RANDOM FOREST
# =====================================

rf = RandomForestClassifier(
    n_estimators=300,
    random_state=42,
    n_jobs=-1
)

rf.fit(
    X_train,
    y_train
)

pred = rf.predict(
    X_test
)

# =====================================
# RESULTS
# =====================================

oa = accuracy_score(
    y_test,
    pred
)

print("\n" + "=" * 50)
print("HEFEI MARGIN CORRECTED + 3x3")
print("=" * 50)

print(
    f"OA = {oa:.6f}"
)

print("\nConfusion Matrix")

print(
    confusion_matrix(
        y_test,
        pred
    )
)

print("\nClassification Report")

print(
    classification_report(
        y_test,
        pred,
        digits=4
    )
)

Labels changed: 59
Saved: ../data2/Hefei/06_3x3/Hefei_3x3_Features_Corrected.csv

==================================================
HEFEI MARGIN CORRECTED + 3x3
==================================================
OA = 0.933111

Confusion Matrix
[[1414   83    4]
 [ 164 1307   24]
 [   8   18 1478]]

Classification Report
              precision    recall  f1-score   support

           1     0.8916    0.9420    0.9161      1501
           2     0.9283    0.8742    0.9004      1495
           3     0.9814    0.9827    0.9821      1504

    accuracy                         0.9331      4500
   macro avg     0.9337    0.9330    0.9329      4500
weighted avg     0.9338    0.9331    0.9329      4500

In [42]:
import pandas as pd

from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import (
    accuracy_score,
    confusion_matrix,
    classification_report
)

# =====================================
# FILES
# =====================================

ORIGINAL_FILE = (
    "../data2/Hefei/01_original/"
    "Hefei_WC_Samples_15000.csv"
)

MANUAL_FILE = (
    "../data2/Hefei/04_manual/"
    "Hefei_BAMS150_Manual.csv"
)

CORRECTED_FILE = (
    "../data2/Hefei/05_corrected/"
    "Hefei_BAMS_Corrected_15000.csv"
)

# =====================================
# LOAD
# =====================================

df = pd.read_csv(ORIGINAL_FILE)

manual = pd.read_csv(MANUAL_FILE)

# =====================================
# APPLY CORRECTIONS
# =====================================

changes = 0

for _, row in manual.iterrows():

    oid = int(row["Original_ID"])
    human = int(row["Human_Class"])

    mask = (
        df["Original_ID"] == oid
    )

    old_class = df.loc[
        mask,
        "Class"
    ].iloc[0]

    if old_class != human:

        df.loc[
            mask,
            "Class"
        ] = human

        changes += 1

print(
    f"Labels changed: {changes}"
)

df.to_csv(
    CORRECTED_FILE,
    index=False
)

# =====================================
# FEATURES
# =====================================

features = [
    "B2",
    "B3",
    "B4",
    "B8",
    "B11",
    "B12",
    "NDVI",
    "NDBI",
    "MNDWI"
]

X = df[features]
y = df["Class"]

# =====================================
# SPLIT
# =====================================

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.3,
    random_state=42,
    stratify=y
)

# =====================================
# RF
# =====================================

rf = RandomForestClassifier(
    n_estimators=300,
    random_state=42,
    n_jobs=-1
)

rf.fit(X_train, y_train)

pred = rf.predict(X_test)

# =====================================
# RESULTS
# =====================================

oa = accuracy_score(
    y_test,
    pred
)

print("\n" + "=" * 50)
print("HEFEI BAMS CORRECTED + PIXEL")
print("=" * 50)

print(
    f"OA = {oa:.6f}"
)

print("\nConfusion Matrix")

print(
    confusion_matrix(
        y_test,
        pred
    )
)

print("\nClassification Report")

print(
    classification_report(
        y_test,
        pred,
        digits=4
    )
)

Labels changed: 122

==================================================
HEFEI BAMS CORRECTED + PIXEL
==================================================
OA = 0.923333

Confusion Matrix
[[1359  131    9]
 [ 128 1328   43]
 [  16   18 1468]]

Classification Report
              precision    recall  f1-score   support

           1     0.9042    0.9066    0.9054      1499
           2     0.8991    0.8859    0.8925      1499
           3     0.9658    0.9774    0.9715      1502

    accuracy                         0.9233      4500
   macro avg     0.9230    0.9233    0.9231      4500
weighted avg     0.9231    0.9233    0.9232      4500

In [43]:
import pandas as pd

from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import (
    accuracy_score,
    confusion_matrix,
    classification_report
)

# =====================================
# FILES
# =====================================

FEATURE_FILE = (
    "../data2/Hefei/06_3x3/"
    "Hefei_3x3_Features.csv"
)

MANUAL_FILE = (
    "../data2/Hefei/04_manual/"
    "Hefei_BAMS150_Manual.csv"
)

CORRECTED_FILE = (
    "../data2/Hefei/06_3x3/"
    "Hefei_BAMS_Corrected_3x3.csv"
)

# =====================================
# LOAD
# =====================================

df = pd.read_csv(FEATURE_FILE)

manual = pd.read_csv(MANUAL_FILE)

# =====================================
# APPLY CORRECTIONS
# =====================================

changes = 0

for _, row in manual.iterrows():

    oid = int(row["Original_ID"])
    human = int(row["Human_Class"])

    mask = (
        df["Original_ID"] == oid
    )

    if mask.sum() == 0:
        continue

    old_class = df.loc[
        mask,
        "Class"
    ].iloc[0]

    if old_class != human:

        df.loc[
            mask,
            "Class"
        ] = human

        changes += 1

print(
    f"Labels changed: {changes}"
)

df.to_csv(
    CORRECTED_FILE,
    index=False
)

# =====================================
# FEATURES
# =====================================

features = [

    "B2_mean","B2_stdDev",

    "B3_mean","B3_stdDev",

    "B4_mean","B4_stdDev",

    "B8_mean","B8_stdDev",

    "B11_mean","B11_stdDev",

    "B12_mean","B12_stdDev",

    "NDVI_mean","NDVI_stdDev",

    "NDBI_mean","NDBI_stdDev",

    "MNDWI_mean","MNDWI_stdDev"
]

X = df[features]
y = df["Class"]

# =====================================
# SPLIT
# =====================================

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.3,
    random_state=42,
    stratify=y
)

# =====================================
# RF
# =====================================

rf = RandomForestClassifier(
    n_estimators=300,
    random_state=42,
    n_jobs=-1
)

rf.fit(X_train, y_train)

pred = rf.predict(X_test)

# =====================================
# RESULTS
# =====================================

oa = accuracy_score(
    y_test,
    pred
)

print("\n" + "=" * 50)
print("HEFEI BAMS CORRECTED + 3x3")
print("=" * 50)

print(
    f"OA = {oa:.6f}"
)

print("\nConfusion Matrix")

print(
    confusion_matrix(
        y_test,
        pred
    )
)

print("\nClassification Report")

print(
    classification_report(
        y_test,
        pred,
        digits=4
    )
)

Labels changed: 122

==================================================
HEFEI BAMS CORRECTED + 3x3
==================================================
OA = 0.935333

Confusion Matrix
[[1403   94    2]
 [ 134 1330   35]
 [  10   16 1476]]

Classification Report
              precision    recall  f1-score   support

           1     0.9069    0.9360    0.9212      1499
           2     0.9236    0.8873    0.9051      1499
           3     0.9755    0.9827    0.9791      1502

    accuracy                         0.9353      4500
   macro avg     0.9354    0.9353    0.9351      4500
weighted avg     0.9354    0.9353    0.9352      4500

In [44]:
import pandas as pd

from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

FILE = (
    "../data2/Nanchang/01_original/"
    "Nanchang_WC_Samples_15000.csv"
)

features = [
    "B2",
    "B3",
    "B4",
    "B8",
    "B11",
    "B12",
    "NDVI",
    "NDBI",
    "MNDWI"
]

df = pd.read_csv(FILE)

X = df[features]
y = df["Class"]

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.3,
    random_state=42,
    stratify=y
)

rf = RandomForestClassifier(
    n_estimators=300,
    random_state=42,
    n_jobs=-1
)

rf.fit(X_train, y_train)

pred = rf.predict(X_test)

oa = accuracy_score(y_test, pred)

print(
    f"Original + Pixel OA = {oa:.6f}"
)

Original + Pixel OA = 0.898222

In [46]:
import pandas as pd

from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

ORIGINAL_FILE = (
    "../data2/Nanchang/01_original/"
    "Nanchang_WC_Samples_15000.csv"
)

MANUAL_FILE = (
    "../data2/Nanchang/04_manual/"
    "Nanchang_Top150_Manual.csv"
)

OUTPUT_FILE = (
    "../data2/Nanchang/05_corrected/"
    "Nanchang_Corrected_15000.csv"
)

df = pd.read_csv(ORIGINAL_FILE)
manual = pd.read_csv(MANUAL_FILE)

changes = 0

for _, row in manual.iterrows():

    oid = int(row["Original_ID"])
    human = int(row["Human_Class"])

    mask = (
        df["Original_ID"] == oid
    )

    old_class = df.loc[
        mask,
        "Class"
    ].iloc[0]

    if old_class != human:

        df.loc[
            mask,
            "Class"
        ] = human

        changes += 1

print(
    f"Labels changed: {changes}"
)

df.to_csv(
    OUTPUT_FILE,
    index=False
)

features = [
    "B2",
    "B3",
    "B4",
    "B8",
    "B11",
    "B12",
    "NDVI",
    "NDBI",
    "MNDWI"
]

X = df[features]
y = df["Class"]

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.3,
    random_state=42,
    stratify=y
)

rf = RandomForestClassifier(
    n_estimators=300,
    random_state=42,
    n_jobs=-1
)

rf.fit(X_train, y_train)

pred = rf.predict(X_test)

oa = accuracy_score(y_test, pred)

print(
    f"Margin Corrected + Pixel OA = {oa:.6f}"
)

Labels changed: 48
Margin Corrected + Pixel OA = 0.907333

In [47]:
import pandas as pd

from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

FILE = (
    "../data2/Nanchang/06_3x3/"
    "Nanchang_3x3_Features.csv"
)

features = [

    "B2_mean","B2_stdDev",
    "B3_mean","B3_stdDev",
    "B4_mean","B4_stdDev",
    "B8_mean","B8_stdDev",

    "B11_mean","B11_stdDev",
    "B12_mean","B12_stdDev",

    "NDVI_mean","NDVI_stdDev",
    "NDBI_mean","NDBI_stdDev",
    "MNDWI_mean","MNDWI_stdDev"
]

df = pd.read_csv(FILE)

X = df[features]
y = df["Class"]

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.3,
    random_state=42,
    stratify=y
)

rf = RandomForestClassifier(
    n_estimators=300,
    random_state=42,
    n_jobs=-1
)

rf.fit(X_train, y_train)

pred = rf.predict(X_test)

oa = accuracy_score(y_test, pred)

print(
    f"Original + 3x3 OA = {oa:.6f}"
)

Original + 3x3 OA = 0.914444

In [48]:
import pandas as pd

from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

FEATURE_FILE = (
    "../data2/Nanchang/06_3x3/"
    "Nanchang_3x3_Features.csv"
)

MANUAL_FILE = (
    "../data2/Nanchang/04_manual/"
    "Nanchang_Top150_Manual.csv"
)

CORRECTED_FILE = (
    "../data2/Nanchang/06_3x3/"
    "Nanchang_3x3_Features_Corrected.csv"
)

df = pd.read_csv(FEATURE_FILE)

manual = pd.read_csv(MANUAL_FILE)

changes = 0

for _, row in manual.iterrows():

    oid = int(row["Original_ID"])
    human = int(row["Human_Class"])

    mask = (
        df["Original_ID"] == oid
    )

    if mask.sum() == 0:
        continue

    old_class = df.loc[
        mask,
        "Class"
    ].iloc[0]

    if old_class != human:

        df.loc[
            mask,
            "Class"
        ] = human

        changes += 1

print(
    f"Labels changed: {changes}"
)

df.to_csv(
    CORRECTED_FILE,
    index=False
)

features = [

    "B2_mean","B2_stdDev",
    "B3_mean","B3_stdDev",
    "B4_mean","B4_stdDev",
    "B8_mean","B8_stdDev",

    "B11_mean","B11_stdDev",
    "B12_mean","B12_stdDev",

    "NDVI_mean","NDVI_stdDev",
    "NDBI_mean","NDBI_stdDev",
    "MNDWI_mean","MNDWI_stdDev"
]

X = df[features]
y = df["Class"]

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.3,
    random_state=42,
    stratify=y
)

rf = RandomForestClassifier(
    n_estimators=300,
    random_state=42,
    n_jobs=-1
)

rf.fit(X_train, y_train)

pred = rf.predict(X_test)

oa = accuracy_score(y_test, pred)

print(
    f"Margin Corrected + 3x3 OA = {oa:.6f}"
)

Labels changed: 48
Margin Corrected + 3x3 OA = 0.910000

In [55]:
import pandas as pd

from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import (
    accuracy_score,
    confusion_matrix,
    classification_report
)

# =====================================
# FILES
# =====================================

ORIGINAL_FILE = (
    "../data2/Nanchang/01_original/"
    "Nanchang_WC_Samples_15000.csv"
)

MANUAL_FILE = (
    "../data2/Nanchang/04_manual/"
    "Nanchang_BAMS150_Manual.csv"
)

CORRECTED_FILE = (
    "../data2/Nanchang/05_corrected/"
    "Nanchang_BAMS_Corrected_15000.csv"
)

# =====================================
# LOAD
# =====================================

df = pd.read_csv(ORIGINAL_FILE)

manual = pd.read_csv(MANUAL_FILE)

# =====================================
# APPLY CORRECTIONS
# =====================================

changes = 0

for _, row in manual.iterrows():

    oid = int(row["Original_ID"])
    human = int(row["Human_Class"])

    mask = (
        df["Original_ID"] == oid
    )

    if mask.sum() == 0:
        print(f"ID NOT FOUND: {oid}")
        continue

    old_class = df.loc[
        mask,
        "Class"
    ].iloc[0]

    if old_class != human:

        df.loc[
            mask,
            "Class"
        ] = human

        changes += 1

# =====================================
# SAVE
# =====================================

df.to_csv(
    CORRECTED_FILE,
    index=False
)

print("\n" + "=" * 50)
print("NANCHANG BAMS CORRECTED FILE UPDATED")
print("=" * 50)

print(f"Labels changed: {changes}")
print(f"Updated file: {CORRECTED_FILE}")

# =====================================
# FEATURES
# =====================================

features = [
    "B2",
    "B3",
    "B4",
    "B8",
    "B11",
    "B12",
    "NDVI",
    "NDBI",
    "MNDWI"
]

X = df[features]
y = df["Class"]

# =====================================
# TRAIN TEST SPLIT
# =====================================

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.3,
    random_state=42,
    stratify=y
)

# =====================================
# RF
# =====================================

rf = RandomForestClassifier(
    n_estimators=300,
    random_state=42,
    n_jobs=-1
)

rf.fit(X_train, y_train)

pred = rf.predict(X_test)

# =====================================
# RESULTS
# =====================================

oa = accuracy_score(
    y_test,
    pred
)

print("\n" + "=" * 50)
print("NANCHANG BAMS CORRECTED + PIXEL")
print("=" * 50)

print(f"OA = {oa:.6f}")

print("\nConfusion Matrix")
print(confusion_matrix(y_test, pred))

print("\nClassification Report")
print(
    classification_report(
        y_test,
        pred,
        digits=4
    )
)

==================================================
NANCHANG BAMS CORRECTED FILE UPDATED
==================================================
Labels changed: 67
Updated file: ../data2/Nanchang/05_corrected/Nanchang_BAMS_Corrected_15000.csv

==================================================
NANCHANG BAMS CORRECTED + PIXEL
==================================================
OA = 0.895778

Confusion Matrix
[[1400   91    8]
 [ 132 1256  113]
 [  52   73 1375]]

Classification Report
              precision    recall  f1-score   support

           1     0.8838    0.9340    0.9082      1499
           2     0.8845    0.8368    0.8600      1501
           3     0.9191    0.9167    0.9179      1500

    accuracy                         0.8958      4500
   macro avg     0.8958    0.8958    0.8954      4500
weighted avg     0.8958    0.8958    0.8953      4500

In [56]:
import pandas as pd

from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import (
    accuracy_score,
    confusion_matrix,
    classification_report
)

# =====================================
# FILES
# =====================================

FEATURE_FILE = (
    "../data2/Nanchang/06_3x3/"
    "Nanchang_3x3_Features.csv"
)

MANUAL_FILE = (
    "../data2/Nanchang/04_manual/"
    "Nanchang_BAMS150_Manual.csv"
)

CORRECTED_FILE = (
    "../data2/Nanchang/06_3x3/"
    "Nanchang_BAMS_Corrected_3x3.csv"
)

# =====================================
# LOAD
# =====================================

df = pd.read_csv(FEATURE_FILE)

manual = pd.read_csv(MANUAL_FILE)

# =====================================
# APPLY CORRECTIONS
# =====================================

changes = 0

for _, row in manual.iterrows():

    oid = int(row["Original_ID"])
    human = int(row["Human_Class"])

    mask = (
        df["Original_ID"] == oid
    )

    if mask.sum() == 0:
        print(f"ID NOT FOUND: {oid}")
        continue

    old_class = df.loc[
        mask,
        "Class"
    ].iloc[0]

    if old_class != human:

        df.loc[
            mask,
            "Class"
        ] = human

        changes += 1

# =====================================
# SAVE
# =====================================

df.to_csv(
    CORRECTED_FILE,
    index=False
)

print("\n" + "=" * 50)
print("NANCHANG BAMS 3x3 FILE UPDATED")
print("=" * 50)

print(f"Labels changed: {changes}")
print(f"Updated file: {CORRECTED_FILE}")

# =====================================
# FEATURES
# =====================================

features = [

    "B2_mean","B2_stdDev",

    "B3_mean","B3_stdDev",

    "B4_mean","B4_stdDev",

    "B8_mean","B8_stdDev",

    "B11_mean","B11_stdDev",

    "B12_mean","B12_stdDev",

    "NDVI_mean","NDVI_stdDev",

    "NDBI_mean","NDBI_stdDev",

    "MNDWI_mean","MNDWI_stdDev"
]

X = df[features]
y = df["Class"]

# =====================================
# SPLIT
# =====================================

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.3,
    random_state=42,
    stratify=y
)

# =====================================
# RF
# =====================================

rf = RandomForestClassifier(
    n_estimators=300,
    random_state=42,
    n_jobs=-1
)

rf.fit(X_train, y_train)

pred = rf.predict(X_test)

# =====================================
# RESULTS
# =====================================

oa = accuracy_score(
    y_test,
    pred
)

print("\n" + "=" * 50)
print("NANCHANG BAMS CORRECTED + 3x3")
print("=" * 50)

print(f"OA = {oa:.6f}")

print("\nConfusion Matrix")
print(confusion_matrix(y_test, pred))

print("\nClassification Report")
print(
    classification_report(
        y_test,
        pred,
        digits=4
    )
)

==================================================
NANCHANG BAMS 3x3 FILE UPDATED
==================================================
Labels changed: 67
Updated file: ../data2/Nanchang/06_3x3/Nanchang_BAMS_Corrected_3x3.csv

==================================================
NANCHANG BAMS CORRECTED + 3x3
==================================================
OA = 0.911778

Confusion Matrix
[[1416   72   11]
 [ 126 1277   98]
 [  26   64 1410]]

Classification Report
              precision    recall  f1-score   support

           1     0.9031    0.9446    0.9234      1499
           2     0.9038    0.8508    0.8765      1501
           3     0.9282    0.9400    0.9341      1500

    accuracy                         0.9118      4500
   macro avg     0.9117    0.9118    0.9113      4500
weighted avg     0.9117    0.9118    0.9113      4500

In [57]:
import pandas as pd

orig = pd.read_csv(
    "../data2/Nanchang/01_original/Nanchang_WC_Samples_15000.csv"
)

manual = pd.read_csv(
    "../data2/Nanchang/04_manual/Nanchang_BAMS150_Manual.csv"
)

merged = manual.merge(
    orig[["Original_ID","Class"]],
    on="Original_ID"
)

merged["Changed"] = (
    merged["Class"]
    !=
    merged["Human_Class"]
)

print(
    merged["Changed"].value_counts()
)

print(
    "Labels changed =",
    merged["Changed"].sum()
)

Changed
False    83
True     67
Name: count, dtype: int64
Labels changed = 67

In [59]:
import pandas as pd

from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

# =====================================
# FILES
# =====================================

ORIGINAL_FILE = (
    "../data2/Nanjing/01_original/"
    "Nanjing_WC_Samples_15000.csv"
)

MANUAL_FILE = (
    "../data2/Nanjing/04_manual/"
    "Nanjing_Top150_Manual.csv"
)

CORRECTED_FILE = (
    "../data2/Nanjing/05_corrected/"
    "Nanjing_Corrected_15000.csv"
)

# =====================================
# LOAD
# =====================================

df = pd.read_csv(ORIGINAL_FILE)

manual = pd.read_csv(MANUAL_FILE)

# =====================================
# APPLY CORRECTIONS
# =====================================

changes = 0

for _, row in manual.iterrows():

    oid = int(row["Original_ID"])
    human = int(row["Human_Class"])

    mask = (
        df["Original_ID"] == oid
    )

    if mask.sum() == 0:
        continue

    old_class = df.loc[
        mask,
        "Class"
    ].iloc[0]

    if old_class != human:

        df.loc[
            mask,
            "Class"
        ] = human

        changes += 1

# =====================================
# SAVE
# =====================================

df.to_csv(
    CORRECTED_FILE,
    index=False
)

print("\n" + "=" * 50)
print("NANJING CORRECTED FILE UPDATED")
print("=" * 50)

print(f"Labels changed: {changes}")
print(f"Updated file: {CORRECTED_FILE}")

# =====================================
# FEATURES
# =====================================

features = [
    "B2",
    "B3",
    "B4",
    "B8",
    "B11",
    "B12",
    "NDVI",
    "NDBI",
    "MNDWI"
]

X = df[features]
y = df["Class"]

# =====================================
# TRAIN / TEST
# =====================================

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.3,
    random_state=42,
    stratify=y
)

rf = RandomForestClassifier(
    n_estimators=300,
    random_state=42,
    n_jobs=-1
)

rf.fit(X_train, y_train)

pred = rf.predict(X_test)

oa = accuracy_score(y_test, pred)

print("\n" + "=" * 50)
print("NANJING MARGIN CORRECTED + PIXEL")
print("=" * 50)

print(f"OA = {oa:.6f}")

==================================================
NANJING CORRECTED FILE UPDATED
==================================================
Labels changed: 36
Updated file: ../data2/Nanjing/05_corrected/Nanjing_Corrected_15000.csv

==================================================
NANJING MARGIN CORRECTED + PIXEL
==================================================
OA = 0.888889

In [60]:
conda activate gee
python scripts/margin_evaluation.py

SyntaxError: invalid syntax (3065912076.py, line 1)

In [63]:
pred_original = pred.copy()

correct_original = (pred_original == y_test).sum()

print(
    "Original correct:",
    correct_original
)

pred_bams = pred.copy()

correct_bams = (pred_bams == y_test).sum()

print(
    "BAMS correct:",
    correct_bams
)

print(
    "Difference:",
    correct_bams - correct_original
)

Original correct: 4000
BAMS correct: 4000
Difference: 0

In [64]:
import numpy as np

changed = np.sum(
    pred_original != pred_bams
)

print("Prediction differences:", changed)

Prediction differences: 0

In [65]:
improved = np.sum(
    (pred_original != y_test)
    &
    (pred_bams == y_test)
)

worsened = np.sum(
    (pred_original == y_test)
    &
    (pred_bams != y_test)
)

print("Improved:", improved)
print("Worsened:", worsened)
print("Net:", improved - worsened)

Improved: 0
Worsened: 0
Net: 0

In [66]:
import numpy as np

improved = np.sum(
    (pred_original != y_test)
    &
    (pred_bams == y_test)
)

worsened = np.sum(
    (pred_original == y_test)
    &
    (pred_bams != y_test)
)

print("Improved:", improved)
print("Worsened:", worsened)
print("Net:", improved - worsened)

Improved: 0
Worsened: 0
Net: 0

In [67]:
np.sum(pred_original != pred_bams)

np.int64(0)

In [68]:
print(id(pred_original))
print(id(pred_bams))

5039172528
4720751888

In [69]:
import pandas as pd

from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

FILE = (
    "../data2/Nanjing/01_original/"
    "Nanjing_WC_Samples_15000.csv"
)

features = [
    "B2",
    "B3",
    "B4",
    "B8",
    "B11",
    "B12",
    "NDVI",
    "NDBI",
    "MNDWI"
]

df = pd.read_csv(FILE)

X = df[features]
y = df["Class"]

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.3,
    random_state=42,
    stratify=y
)

rf = RandomForestClassifier(
    n_estimators=300,
    random_state=42,
    n_jobs=-1
)

rf.fit(X_train, y_train)

pred = rf.predict(X_test)

oa = accuracy_score(y_test, pred)

print(
    f"Original + Pixel OA = {oa:.6f}"
)

Original + Pixel OA = 0.891111

In [71]:
import pandas as pd

from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

ORIGINAL_FILE = (
    "../data2/Nanjing/01_original/"
    "Nanjing_WC_Samples_15000.csv"
)

MANUAL_FILE = (
    "../data2/Nanjing/04_manual/"
    "Nanjing_BAMS150_Manual.csv"
)

CORRECTED_FILE = (
    "../data2/Nanjing/05_corrected/"
    "Nanjing_BAMS_Corrected_15000.csv"
)

df = pd.read_csv(ORIGINAL_FILE)
manual = pd.read_csv(MANUAL_FILE)

changes = 0

for _, row in manual.iterrows():

    oid = int(row["Original_ID"])
    human = int(row["Human_Class"])

    mask = df["Original_ID"] == oid

    old_class = df.loc[
        mask,
        "Class"
    ].iloc[0]

    if old_class != human:

        df.loc[
            mask,
            "Class"
        ] = human

        changes += 1

df.to_csv(
    CORRECTED_FILE,
    index=False
)

print("\n==============================")
print("NANJING BAMS FILE UPDATED")
print("==============================")

print(
    f"Labels changed: {changes}"
)

features = [
    "B2",
    "B3",
    "B4",
    "B8",
    "B11",
    "B12",
    "NDVI",
    "NDBI",
    "MNDWI"
]

X = df[features]
y = df["Class"]

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.3,
    random_state=42,
    stratify=y
)

rf = RandomForestClassifier(
    n_estimators=300,
    random_state=42,
    n_jobs=-1
)

rf.fit(X_train, y_train)

pred = rf.predict(X_test)

oa = accuracy_score(y_test, pred)

print(
    f"NANJING BAMS CORRECTED + PIXEL OA = {oa:.6f}"
)

==============================
NANJING BAMS FILE UPDATED
==============================
Labels changed: 69
NANJING BAMS CORRECTED + PIXEL OA = 0.891111

In [72]:
import pandas as pd

from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

FILE = (
    "../data2/Nanjing/06_3x3/"
    "Nanjing_3x3_Features.csv"
)

features = [

    "B2_mean","B2_stdDev",
    "B3_mean","B3_stdDev",
    "B4_mean","B4_stdDev",
    "B8_mean","B8_stdDev",

    "B11_mean","B11_stdDev",
    "B12_mean","B12_stdDev",

    "NDVI_mean","NDVI_stdDev",
    "NDBI_mean","NDBI_stdDev",
    "MNDWI_mean","MNDWI_stdDev"
]

df = pd.read_csv(FILE)

X = df[features]
y = df["Class"]

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.3,
    random_state=42,
    stratify=y
)

rf = RandomForestClassifier(
    n_estimators=300,
    random_state=42,
    n_jobs=-1
)

rf.fit(X_train, y_train)

pred = rf.predict(X_test)

oa = accuracy_score(y_test, pred)

print(
    f"Original + 3x3 OA = {oa:.6f}"
)

Original + 3x3 OA = 0.903111

In [73]:
import pandas as pd

from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

FEATURE_FILE = (
    "../data2/Nanjing/06_3x3/"
    "Nanjing_3x3_Features.csv"
)

MANUAL_FILE = (
    "../data2/Nanjing/04_manual/"
    "Nanjing_BAMS150_Manual.csv"
)

CORRECTED_FILE = (
    "../data2/Nanjing/06_3x3/"
    "Nanjing_BAMS_Corrected_3x3.csv"
)

df = pd.read_csv(FEATURE_FILE)
manual = pd.read_csv(MANUAL_FILE)

changes = 0

for _, row in manual.iterrows():

    oid = int(row["Original_ID"])
    human = int(row["Human_Class"])

    mask = (
        df["Original_ID"] == oid
    )

    old_class = df.loc[
        mask,
        "Class"
    ].iloc[0]

    if old_class != human:

        df.loc[
            mask,
            "Class"
        ] = human

        changes += 1

df.to_csv(
    CORRECTED_FILE,
    index=False
)

print("\n==============================")
print("NANJING BAMS 3x3 FILE UPDATED")
print("==============================")

print(
    f"Labels changed: {changes}"
)

features = [

    "B2_mean","B2_stdDev",
    "B3_mean","B3_stdDev",
    "B4_mean","B4_stdDev",
    "B8_mean","B8_stdDev",

    "B11_mean","B11_stdDev",
    "B12_mean","B12_stdDev",

    "NDVI_mean","NDVI_stdDev",
    "NDBI_mean","NDBI_stdDev",
    "MNDWI_mean","MNDWI_stdDev"
]

X = df[features]
y = df["Class"]

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.3,
    random_state=42,
    stratify=y
)

rf = RandomForestClassifier(
    n_estimators=300,
    random_state=42,
    n_jobs=-1
)

rf.fit(X_train, y_train)

pred = rf.predict(X_test)

oa = accuracy_score(y_test, pred)

print(
    f"NANJING BAMS CORRECTED + 3x3 OA = {oa:.6f}"
)

==============================
NANJING BAMS 3x3 FILE UPDATED
==============================
Labels changed: 69
NANJING BAMS CORRECTED + 3x3 OA = 0.910000

In [75]:
import pandas as pd
import numpy as np

from sklearn.preprocessing import StandardScaler
from sklearn.neighbors import NearestNeighbors

# =====================================
# FILES
# =====================================

ORIGINAL_FILE = (
    "../data2/Nanjing/01_original/"
    "Nanjing_WC_Samples_15000.csv"
)

MANUAL_FILE = (
    "../data2/Nanjing/04_manual/"
    "Nanjing_BAMS150_Manual.csv"
)

OUTPUT_FILE = (
    "../data2/Nanjing/05_corrected/"
    "Nanjing_BAMS_Propagated_15000.csv"
)

# =====================================
# FEATURES
# =====================================

features = [
    "B2",
    "B3",
    "B4",
    "B8",
    "B11",
    "B12",
    "NDVI",
    "NDBI",
    "MNDWI"
]

# =====================================
# LOAD
# =====================================

df = pd.read_csv(ORIGINAL_FILE)

manual = pd.read_csv(MANUAL_FILE)

manual["Human_Class"] = pd.to_numeric(
    manual["Human_Class"],
    errors="coerce"
)

manual = manual[
    manual["Human_Class"].notna()
]

# =====================================
# ONLY CHANGED LABELS
# =====================================

merged = manual.merge(
    df[
        ["Original_ID", "Class"]
    ],
    on="Original_ID"
)

changed = merged[
    merged["Class"]
    !=
    merged["Human_Class"]
].copy()

print(
    "Changed labels:",
    len(changed)
)

# =====================================
# NORMALIZE FEATURES
# =====================================

X = df[features].values

scaler = StandardScaler()

X_scaled = scaler.fit_transform(X)

# =====================================
# KNN
# =====================================

k = 20

nn = NearestNeighbors(
    n_neighbors=k+1,
    metric="euclidean"
)

nn.fit(X_scaled)

# =====================================
# PROPAGATION
# =====================================

propagated = 0

for _, row in changed.iterrows():

    oid = int(row["Original_ID"])

    human_class = int(
        row["Human_Class"]
    )

    idx = df.index[
        df["Original_ID"] == oid
    ][0]

    distances, neighbors = nn.kneighbors(
        X_scaled[idx].reshape(1,-1)
    )

    neighbors = neighbors[0][1:]

    for n in neighbors:

        current = int(
            df.loc[n,"Class"]
        )

        if current != human_class:

            df.loc[
                n,
                "Class"
            ] = human_class

            propagated += 1

print(
    "Propagated labels:",
    propagated
)

# =====================================
# SAVE
# =====================================

df.to_csv(
    OUTPUT_FILE,
    index=False
)

print(
    "\nSaved:"
)

print(
    OUTPUT_FILE
)

Changed labels: 69
Propagated labels: 432

Saved:
../data2/Nanjing/05_corrected/Nanjing_BAMS_Propagated_15000.csv

In [76]:
orig = pd.read_csv(
    "../data2/Nanjing/01_original/Nanjing_WC_Samples_15000.csv"
)

prop = pd.read_csv(
    "../data2/Nanjing/05_corrected/Nanjing_BAMS_Propagated_15000.csv"
)

changed = (
    orig["Class"] != prop["Class"]
)

print(
    "Total changed:",
    changed.sum()
)

diff = pd.DataFrame({
    "old": orig["Class"],
    "new": prop["Class"]
})

print(
    diff[orig["Class"] != prop["Class"]]
    .groupby(["old","new"])
    .size()
    .sort_values(ascending=False)
)

Total changed: 424
old  new
1    2      169
     3      114
2    3       56
     1       41
3    2       40
     1        4
dtype: int64

In [78]:
import pandas as pd
import numpy as np

from sklearn.preprocessing import StandardScaler
from sklearn.neighbors import NearestNeighbors

# =====================================
# FILES
# =====================================

ORIGINAL_FILE = (
    "../data2/Nanjing/01_original/"
    "Nanjing_WC_Samples_15000.csv"
)

MANUAL_FILE = (
    "../data2/Nanjing/04_manual/"
    "Nanjing_BAMS150_Manual.csv"
)

OUTPUT_FILE = (
    "../data2/Nanjing/05_corrected/"
    "Nanjing_BAMS_Propagated_v2.csv"
)

# =====================================
# PARAMETERS
# =====================================

k = 10

support_ratio = 0.8

# =====================================
# FEATURES
# =====================================

features = [
    "B2",
    "B3",
    "B4",
    "B8",
    "B11",
    "B12",
    "NDVI",
    "NDBI",
    "MNDWI"
]

# =====================================
# LOAD
# =====================================

df = pd.read_csv(ORIGINAL_FILE)

manual = pd.read_csv(MANUAL_FILE)

manual["Human_Class"] = pd.to_numeric(
    manual["Human_Class"],
    errors="coerce"
)

manual = manual[
    manual["Human_Class"].notna()
]

# =====================================
# FIND TRUE CHANGES
# =====================================

merged = manual.merge(
    df[
        ["Original_ID", "Class"]
    ],
    on="Original_ID"
)

changed = merged[
    merged["Class"]
    !=
    merged["Human_Class"]
].copy()

print(
    "Manual corrected:",
    len(changed)
)

# =====================================
# NORMALIZE
# =====================================

X = df[features].values

scaler = StandardScaler()

X_scaled = scaler.fit_transform(X)

# =====================================
# KNN
# =====================================

nn = NearestNeighbors(
    n_neighbors=k + 1,
    metric="euclidean"
)

nn.fit(X_scaled)

# =====================================
# PROPAGATION
# =====================================

propagated = 0

for _, row in changed.iterrows():

    oid = int(row["Original_ID"])

    human_class = int(
        row["Human_Class"]
    )

    idx = df.index[
        df["Original_ID"] == oid
    ][0]

    distances, neighbors = nn.kneighbors(
        X_scaled[idx].reshape(1, -1)
    )

    neighbors = neighbors[0][1:]

    neighbor_classes = (
        df.loc[
            neighbors,
            "Class"
        ]
        .astype(int)
    )

    ratio = (
        neighbor_classes
        ==
        human_class
    ).mean()

    if ratio < support_ratio:
        continue

    for n in neighbors:

        current = int(
            df.loc[n, "Class"]
        )

        if current != human_class:

            df.loc[
                n,
                "Class"
            ] = human_class

            propagated += 1

# =====================================
# SAVE
# =====================================

df.to_csv(
    OUTPUT_FILE,
    index=False
)

print(
    "\nPropagation Summary"
)

print(
    "Manual corrections:",
    len(changed)
)

print(
    "Propagated labels:",
    propagated
)

print(
    "Total impact:",
    len(changed) + propagated
)

print(
    "\nSaved:"
)

print(
    OUTPUT_FILE
)

Manual corrected: 69

Propagation Summary
Manual corrections: 69
Propagated labels: 35
Total impact: 104

Saved:
../data2/Nanjing/05_corrected/Nanjing_BAMS_Propagated_v2.csv

In [ ]:
import pandas as pd

feat = pd.read_csv(
    "../data2/Nanjing/06_3x3/Nanjing_3x3_Features.csv"
)

prop = pd.read_csv(
    "../data2/Nanjing/05_corrected/Nanjing_BAMS_Propagated_v2.csv"
)

class_map = prop.set_index(
    "Original_ID"
)["Class"]

feat["Class"] = (
    feat["Original_ID"]
    .map(class_map)
)

feat.to_csv(
    "../data2/Nanjing/06_3x3/Nanjing_BAMS_Propagated_v2_3x3.csv",
    index=False
)

print(
    "Nanjing_BAMS_Propagated_v2_3x3.csv saved"
)

Nanjing_BAMS_Propagated_v2_3x3.csv saved

In [80]:
import pandas as pd

from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

FILE = (
    "../data2/Nanjing/06_3x3/"
    "Nanjing_BAMS_Propagated_v2_3x3.csv"
)

features = [

    "B2_mean","B2_stdDev",

    "B3_mean","B3_stdDev",

    "B4_mean","B4_stdDev",

    "B8_mean","B8_stdDev",

    "B11_mean","B11_stdDev",

    "B12_mean","B12_stdDev",

    "NDVI_mean","NDVI_stdDev",

    "NDBI_mean","NDBI_stdDev",

    "MNDWI_mean","MNDWI_stdDev"
]

df = pd.read_csv(FILE)

X = df[features]
y = df["Class"]

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.3,
    random_state=42,
    stratify=y
)

rf = RandomForestClassifier(
    n_estimators=300,
    random_state=42,
    n_jobs=-1
)

rf.fit(X_train, y_train)

pred = rf.predict(X_test)

oa = accuracy_score(
    y_test,
    pred
)

print("\n==============================")
print("NANJING BAMS + PROPAGATION + 3x3")
print("==============================")

print(
    f"OA = {oa:.6f}"
)

==============================
NANJING BAMS + PROPAGATION + 3x3
==============================
OA = 0.911778

In [83]:
import pandas as pd
import numpy as np

from sklearn.preprocessing import StandardScaler
from sklearn.neighbors import NearestNeighbors

# =====================================
# FILES
# =====================================

ORIGINAL_FILE = (
    "../data2/Nanjing/01_original/"
    "Nanjing_WC_Samples_15000.csv"
)

MANUAL_FILE = (
    "../data2/Nanjing/04_manual/"
    "Nanjing_BAMS150_Manual.csv"
)

OUTPUT_FILE = (
    "../data2/Nanjing/05_corrected/"
    "Nanjing_BAMS_Propagated_v3.csv"
)

# =====================================
# PARAMETERS
# =====================================

k = 15

support_ratio = 0.7

# =====================================
# FEATURES
# =====================================

features = [
    "B2",
    "B3",
    "B4",
    "B8",
    "B11",
    "B12",
    "NDVI",
    "NDBI",
    "MNDWI"
]

# =====================================
# LOAD
# =====================================

df = pd.read_csv(ORIGINAL_FILE)

manual = pd.read_csv(MANUAL_FILE)

manual["Human_Class"] = pd.to_numeric(
    manual["Human_Class"],
    errors="coerce"
)

manual = manual[
    manual["Human_Class"].notna()
]

# =====================================
# FIND TRUE CHANGES
# =====================================

merged = manual.merge(
    df[
        ["Original_ID", "Class"]
    ],
    on="Original_ID"
)

changed = merged[
    merged["Class"]
    !=
    merged["Human_Class"]
].copy()

print(
    "Manual corrected:",
    len(changed)
)

# =====================================
# NORMALIZE FEATURES
# =====================================

X = df[features].values

scaler = StandardScaler()

X_scaled = scaler.fit_transform(X)

# =====================================
# KNN
# =====================================

nn = NearestNeighbors(
    n_neighbors=k + 1,
    metric="euclidean"
)

nn.fit(X_scaled)

# =====================================
# PROPAGATION
# =====================================

propagated = 0

for _, row in changed.iterrows():

    oid = int(row["Original_ID"])

    human_class = int(
        row["Human_Class"]
    )

    idx = df.index[
        df["Original_ID"] == oid
    ][0]

    distances, neighbors = nn.kneighbors(
        X_scaled[idx].reshape(1, -1)
    )

    neighbors = neighbors[0][1:]

    neighbor_classes = (
        df.loc[
            neighbors,
            "Class"
        ]
        .astype(int)
    )

    ratio = (
        neighbor_classes
        ==
        human_class
    ).mean()

    if ratio < support_ratio:
        continue

    for n in neighbors:

        current = int(
            df.loc[n, "Class"]
        )

        if current != human_class:

            df.loc[
                n,
                "Class"
            ] = human_class

            propagated += 1

# =====================================
# SAVE
# =====================================

df.to_csv(
    OUTPUT_FILE,
    index=False
)

print("\nPropagation Summary")

print(
    "Manual corrections:",
    len(changed)
)

print(
    "Propagated labels:",
    propagated
)

print(
    "Total impact:",
    len(changed) + propagated
)

print("\nSaved:")

print(
    OUTPUT_FILE
)

Manual corrected: 69

Propagation Summary
Manual corrections: 69
Propagated labels: 65
Total impact: 134

Saved:
../data2/Nanjing/05_corrected/Nanjing_BAMS_Propagated_v3.csv

In [84]:
orig = pd.read_csv(
    "../data2/Nanjing/01_original/Nanjing_WC_Samples_15000.csv"
)

prop = pd.read_csv(
    "../data2/Nanjing/05_corrected/Nanjing_BAMS_Propagated_v3.csv"
)

changed = (
    orig["Class"] != prop["Class"]
)

print(
    "Total changed:",
    changed.sum()
)

diff = pd.DataFrame({
    "old": orig["Class"],
    "new": prop["Class"]
})

print(
    diff[changed]
    .groupby(["old","new"])
    .size()
    .sort_values(ascending=False)
)

Total changed: 65
old  new
1    2      31
2    1      30
3    1       3
     2       1
dtype: int64

In [85]:
import pandas as pd

feat = pd.read_csv(
    "../data2/Nanjing/06_3x3/Nanjing_3x3_Features.csv"
)

prop = pd.read_csv(
    "../data2/Nanjing/05_corrected/Nanjing_BAMS_Propagated_15000.csv"
)

class_map = prop.set_index(
    "Original_ID"
)["Class"]

feat["Class"] = (
    feat["Original_ID"]
    .map(class_map)
)

feat.to_csv(
    "../data2/Nanjing/06_3x3/Nanjing_BAMS_Propagated_3x3.csv",
    index=False
)

print(
    "Nanjing_BAMS_Propagated_3x3.csv saved"
)

Nanjing_BAMS_Propagated_3x3.csv saved

In [86]:
import pandas as pd

from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

FILE = (
    "../data2/Nanjing/06_3x3/"
    "Nanjing_BAMS_Propagated_3x3.csv"
)

features = [

    "B2_mean","B2_stdDev",
    "B3_mean","B3_stdDev",
    "B4_mean","B4_stdDev",
    "B8_mean","B8_stdDev",

    "B11_mean","B11_stdDev",
    "B12_mean","B12_stdDev",

    "NDVI_mean","NDVI_stdDev",
    "NDBI_mean","NDBI_stdDev",
    "MNDWI_mean","MNDWI_stdDev"
]

df = pd.read_csv(FILE)

X = df[features]
y = df["Class"]

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.3,
    random_state=42,
    stratify=y
)

rf = RandomForestClassifier(
    n_estimators=300,
    random_state=42,
    n_jobs=-1
)

rf.fit(X_train, y_train)

pred = rf.predict(X_test)

oa = accuracy_score(y_test, pred)

print("\n==============================")
print("NANJING BAMS + PROPAGATION V1 + 3x3")
print("==============================")

print(
    f"OA = {oa:.6f}"
)

==============================
NANJING BAMS + PROPAGATION V1 + 3x3
==============================
OA = 0.899111

In [87]:
import pandas as pd

ORIGINAL_FILE = (
    "../data2/Nanjing/01_original/"
    "Nanjing_WC_Samples_15000.csv"
)

MANUAL_FILE = (
    "../data2/Nanjing/04_manual/"
    "Nanjing_BAMS150_Manual.csv"
)

orig = pd.read_csv(ORIGINAL_FILE)

manual = pd.read_csv(MANUAL_FILE)

manual["Human_Class"] = pd.to_numeric(
    manual["Human_Class"],
    errors="coerce"
)

manual = manual[
    manual["Human_Class"].notna()
]

merged = manual.merge(
    orig[["Original_ID", "Class"]],
    on="Original_ID"
)

correct = (
    merged["Class"]
    ==
    merged["Human_Class"]
).sum()

wrong = (
    merged["Class"]
    !=
    merged["Human_Class"]
).sum()

total = len(merged)

accuracy = correct / total
error_rate = wrong / total

print("\n==============================")
print("NANJING BAMS ACCURACY")
print("==============================")

print("Correct:", correct)
print("Wrong:", wrong)
print("Total:", total)

print(
    f"Accuracy = {accuracy:.4f}"
)

print(
    f"Error Rate = {error_rate:.4f}"
)

==============================
NANJING BAMS ACCURACY
==============================
Correct: 54
Wrong: 96
Total: 150
Accuracy = 0.3600
Error Rate = 0.6400

In [88]:
import pandas as pd

from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

ORIGINAL_FILE = (
    "../data2/Nanjing/01_original/"
    "Nanjing_WC_Samples_15000.csv"
)

MANUAL_FILE = (
    "../data2/Nanjing/04_manual/"
    "Nanjing_BAMS150_Manual.csv"
)

CORRECTED_FILE = (
    "../data2/Nanjing/05_corrected/"
    "Nanjing_BAMS_Corrected_15000.csv"
)

df = pd.read_csv(ORIGINAL_FILE)

manual = pd.read_csv(MANUAL_FILE)

changes = 0

for _, row in manual.iterrows():

    if pd.isna(row["Human_Class"]):
        continue

    oid = int(row["Original_ID"])
    human = int(row["Human_Class"])

    mask = (
        df["Original_ID"] == oid
    )

    old_class = df.loc[
        mask,
        "Class"
    ].iloc[0]

    if old_class != human:

        df.loc[
            mask,
            "Class"
        ] = human

        changes += 1

df.to_csv(
    CORRECTED_FILE,
    index=False
)

print(
    f"\nLabels changed: {changes}"
)

features = [
    "B2",
    "B3",
    "B4",
    "B8",
    "B11",
    "B12",
    "NDVI",
    "NDBI",
    "MNDWI"
]

X = df[features]
y = df["Class"]

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.3,
    random_state=42,
    stratify=y
)

rf = RandomForestClassifier(
    n_estimators=300,
    random_state=42,
    n_jobs=-1
)

rf.fit(X_train, y_train)

pred = rf.predict(X_test)

oa = accuracy_score(
    y_test,
    pred
)

print("\n==============================")
print("NANJING BAMS + PIXEL")
print("==============================")

print(
    f"OA = {oa:.6f}"
)

Labels changed: 96

==============================
NANJING BAMS + PIXEL
==============================
OA = 0.894889

In [112]:
import pandas as pd

from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

FEATURE_FILE = (
    "../data2/Nanchang/06_3x3/"
    "Nanchang_3x3_Features.csv"
)

MANUAL_FILE = (
    "../data2/Nanchang/04_manual/"
    "Nanchang_BAMS150_Manual.csv"
)

CORRECTED_FILE = (
    "../data2/Nanchang/06_3x3/"
    "Nanchang_BAMS_Corrected_3x3.csv"
)

df = pd.read_csv(FEATURE_FILE)

manual = pd.read_csv(MANUAL_FILE)

changes = 0

for _, row in manual.iterrows():

    if pd.isna(row["Human_Class"]):
        continue

    oid = int(row["Original_ID"])
    human = int(row["Human_Class"])

    mask = (
        df["Original_ID"] == oid
    )

    old_class = df.loc[
        mask,
        "Class"
    ].iloc[0]

    if old_class != human:

        df.loc[
            mask,
            "Class"
        ] = human

        changes += 1

df.to_csv(
    CORRECTED_FILE,
    index=False
)

print(
    f"\nLabels changed: {changes}"
)

features = [

    "B2_mean","B2_stdDev",
    "B3_mean","B3_stdDev",
    "B4_mean","B4_stdDev",
    "B8_mean","B8_stdDev",

    "B11_mean","B11_stdDev",
    "B12_mean","B12_stdDev",

    "NDVI_mean","NDVI_stdDev",
    "NDBI_mean","NDBI_stdDev",
    "MNDWI_mean","MNDWI_stdDev"
]

X = df[features]
y = df["Class"]

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.3,
    random_state=42,
    stratify=y
)

rf = RandomForestClassifier(
    n_estimators=300,
    random_state=42,
    n_jobs=-1
)

rf.fit(X_train, y_train)

pred = rf.predict(X_test)

oa = accuracy_score(
    y_test,
    pred
)

print("\n==============================")
print("Nanchang BAMS + 3x3")
print("==============================")

print(
    f"OA = {oa:.6f}"
)

Labels changed: 67

==============================
Nanchang BAMS + 3x3
==============================
OA = 0.911778

In [95]:
import pandas as pd

from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

ORIGINAL_FILE = (
    "../data2/Nanjing/01_original/"
    "Nanjing_WC_Samples_15000.csv"
)

MANUAL_FILE = (
    "../data2/Nanjing/04_manual/"
    "Nanjing_Top150_Manual.csv"
)

CORRECTED_FILE = (
    "../data2/Nanjing/05_corrected/"
    "Nanjing_Corrected_15000.csv"
)

df = pd.read_csv(ORIGINAL_FILE)

manual = pd.read_csv(MANUAL_FILE)

changes = 0

for _, row in manual.iterrows():

    if pd.isna(row["Human_Class"]):
        continue

    oid = int(row["Original_ID"])
    human = int(row["Human_Class"])

    mask = (
        df["Original_ID"] == oid
    )

    old_class = df.loc[
        mask,
        "Class"
    ].iloc[0]

    if old_class != human:

        df.loc[
            mask,
            "Class"
        ] = human

        changes += 1

df.to_csv(
    CORRECTED_FILE,
    index=False
)

print(
    f"\nLabels changed: {changes}"
)

features = [
    "B2","B3","B4","B8",
    "B11","B12",
    "NDVI","NDBI","MNDWI"
]

X = df[features]
y = df["Class"]

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.3,
    random_state=42,
    stratify=y
)

rf = RandomForestClassifier(
    n_estimators=300,
    random_state=42,
    n_jobs=-1
)

rf.fit(X_train, y_train)

pred = rf.predict(X_test)

oa = accuracy_score(y_test, pred)

print("\n==============================")
print("NANJING MARGIN + PIXEL")
print("==============================")

print(
    f"OA = {oa:.6f}"
)

Labels changed: 69

==============================
NANJING MARGIN + PIXEL
==============================
OA = 0.895556

In [94]:
import pandas as pd

from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

FEATURE_FILE = (
    "../data2/Nanjing/06_3x3/"
    "Nanjing_3x3_Features.csv"
)

MANUAL_FILE = (
    "../data2/Nanjing/04_manual/"
    "Nanjing_Top150_Manual.csv"
)

CORRECTED_FILE = (
    "../data2/Nanjing/06_3x3/"
    "Nanjing_3x3_Features_Corrected.csv"
)

df = pd.read_csv(FEATURE_FILE)

manual = pd.read_csv(MANUAL_FILE)

changes = 0

for _, row in manual.iterrows():

    if pd.isna(row["Human_Class"]):
        continue

    oid = int(row["Original_ID"])
    human = int(row["Human_Class"])

    mask = (
        df["Original_ID"] == oid
    )

    old_class = df.loc[
        mask,
        "Class"
    ].iloc[0]

    if old_class != human:

        df.loc[
            mask,
            "Class"
        ] = human

        changes += 1

df.to_csv(
    CORRECTED_FILE,
    index=False
)

print(
    f"\nLabels changed: {changes}"
)

features = [

    "B2_mean","B2_stdDev",
    "B3_mean","B3_stdDev",
    "B4_mean","B4_stdDev",
    "B8_mean","B8_stdDev",

    "B11_mean","B11_stdDev",
    "B12_mean","B12_stdDev",

    "NDVI_mean","NDVI_stdDev",
    "NDBI_mean","NDBI_stdDev",
    "MNDWI_mean","MNDWI_stdDev"
]

X = df[features]
y = df["Class"]

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.3,
    random_state=42,
    stratify=y
)

rf = RandomForestClassifier(
    n_estimators=300,
    random_state=42,
    n_jobs=-1
)

rf.fit(X_train, y_train)

pred = rf.predict(X_test)

oa = accuracy_score(y_test, pred)

print("\n==============================")
print("NANJING MARGIN + 3x3")
print("==============================")

print(
    f"OA = {oa:.6f}"
)

Labels changed: 69

==============================
NANJING MARGIN + 3x3
==============================
OA = 0.914000

In [96]:
import pandas as pd

from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import classification_report
from sklearn.model_selection import train_test_split

# =====================================
# FILES
# =====================================

ORIGINAL_FILE = (
    "../data2/Nanjing/01_original/"
    "Nanjing_WC_Samples_15000.csv"
)

MANUAL_FILE = (
    "../data2/Nanjing/04_manual/"
    "Nanjing_BAMS150_Manual.csv"
)

# =====================================
# LOAD
# =====================================

orig = pd.read_csv(ORIGINAL_FILE)

manual = pd.read_csv(MANUAL_FILE)

manual["Human_Class"] = pd.to_numeric(
    manual["Human_Class"],
    errors="coerce"
)

manual = manual[
    manual["Human_Class"].notna()
]

# =====================================
# CREATE ERROR LABEL
# =====================================

merged = manual.merge(
    orig,
    on="Original_ID"
)

merged["Error_Label"] = (
    merged["Class"]
    !=
    merged["Human_Class"]
).astype(int)

print("\nError Statistics")

print(
    merged["Error_Label"]
    .value_counts()
)

# =====================================
# FEATURES
# =====================================

features = [
    "B2",
    "B3",
    "B4",
    "B8",
    "B11",
    "B12",
    "NDVI",
    "NDBI",
    "MNDWI"
]

X = merged[features]

y = merged["Error_Label"]

# =====================================
# TRAIN
# =====================================

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.3,
    random_state=42,
    stratify=y
)

rf = RandomForestClassifier(
    n_estimators=500,
    random_state=42,
    n_jobs=-1
)

rf.fit(
    X_train,
    y_train
)

pred = rf.predict(X_test)

print("\nClassification Report")

print(
    classification_report(
        y_test,
        pred,
        digits=4
    )
)

# =====================================
# FEATURE IMPORTANCE
# =====================================

imp = pd.DataFrame({
    "Feature": features,
    "Importance": rf.feature_importances_
})

imp = imp.sort_values(
    "Importance",
    ascending=False
)

print("\nTop Features")

print(imp)

Error Statistics
Error_Label
1    96
0    54
Name: count, dtype: int64

Classification Report
              precision    recall  f1-score   support

           0     0.5000    0.5000    0.5000        16
           1     0.7241    0.7241    0.7241        29

    accuracy                         0.6444        45
   macro avg     0.6121    0.6121    0.6121        45
weighted avg     0.6444    0.6444    0.6444        45


Top Features
  Feature  Importance
7    NDBI    0.181799
6    NDVI    0.176407
3      B8    0.120474
0      B2    0.107832
8   MNDWI    0.087358
1      B3    0.083591
2      B4    0.082658
5     B12    0.080427
4     B11    0.079453

In [97]:
X_all = orig[features]

prob_error = rf.predict_proba(
    X_all
)[:,1]

orig["Error_Probability"] = prob_error

suspects = (
    orig
    .sort_values(
        "Error_Probability",
        ascending=False
    )
)

suspects.to_csv(
    "../data2/Nanjing/07_results/"
    "Nanjing_ErrorCandidates.csv",
    index=False
)

print(
    suspects[
        [
            "Original_ID",
            "Class",
            "Error_Probability"
        ]
    ].head(100)
)

      Original_ID  Class  Error_Probability
5782         5782      2              0.996
5799         5799      2              0.996
7294         7294      2              0.996
8131         8131      2              0.994
6195         6195      2              0.994
...           ...    ...                ...
6717         6717      2              0.986
9152         9152      2              0.986
6331         6331      2              0.986
7834         7834      2              0.986
8113         8113      2              0.986

[100 rows x 3 columns]

In [101]:
top20 = suspects.head(20)

print(
    top20[
        [
            "Original_ID",
            "Class",
            "Error_Probability"
        ]
    ]
)

      Original_ID  Class  Error_Probability
5782         5782      2              0.996
5799         5799      2              0.996
7294         7294      2              0.996
8131         8131      2              0.994
6195         6195      2              0.994
7514         7514      2              0.994
7808         7808      2              0.994
5635         5635      2              0.994
6138         6138      2              0.994
8956         8956      2              0.994
5423         5423      2              0.994
8535         8535      2              0.994
6941         6941      2              0.994
5341         5341      2              0.994
5529         5529      2              0.994
5855         5855      2              0.994
9521         9521      2              0.992
9158         9158      2              0.992
5399         5399      2              0.992
3238         3238      1              0.992

In [102]:
top20 = suspects.head(20)

top20 = top20[
    [
        "Original_ID",
        "lon",
        "lat",
        "Class",
        "Error_Probability"
    ]
]

top20.to_csv(
    "../data2/Nanjing/07_results/Nanjing_Top20_ErrorCandidates.csv",
    index=False
)

print(top20)

      Original_ID         lon        lat  Class  Error_Probability
5782         5782  118.925131  32.479353      2              0.996
5799         5799  119.109824  31.897155      2              0.996
7294         7294  118.934922  32.470190      2              0.996
8131         8131  118.828562  32.248396      2              0.994
6195         6195  118.674860  32.286125      2              0.994
7514         7514  118.730915  32.358799      2              0.994
7808         7808  118.717350  32.589576      2              0.994
5635         5635  118.737024  32.400481      2              0.994
6138         6138  119.084672  31.931380      2              0.994
8956         8956  118.791192  32.481329      2              0.994
5423         5423  118.768824  32.391138      2              0.994
8535         8535  118.931688  32.293222      2              0.994
6941         6941  118.596707  31.990939      2              0.994
5341         5341  118.929083  32.485910      2              0.994
5529         5529  118.901685  31.558400      2              0.994
5855         5855  119.115574  31.703927      2              0.994
9521         9521  118.955224  32.333017      2              0.992
9158         9158  118.628956  32.209319      2              0.992
5399         5399  119.017837  32.495971      2              0.992
3238         3238  118.931419  31.951143      1              0.992

In [103]:
import pandas as pd

from sklearn.ensemble import RandomForestClassifier

# =====================================
# FILES
# =====================================

ORIGINAL_FILE = (
    "../data2/Nanjing/01_original/"
    "Nanjing_WC_Samples_15000.csv"
)

MANUAL_FILE = (
    "../data2/Nanjing/04_manual/"
    "Nanjing_BAMS150_Manual.csv"
)

# =====================================
# LOAD
# =====================================

orig = pd.read_csv(ORIGINAL_FILE)

manual = pd.read_csv(MANUAL_FILE)

manual["Human_Class"] = pd.to_numeric(
    manual["Human_Class"],
    errors="coerce"
)

manual = manual[
    manual["Human_Class"].notna()
]

# =====================================
# MERGE
# =====================================

train_df = manual.merge(
    orig,
    on="Original_ID"
)

# =====================================
# FEATURES
# =====================================

features = [
    "B2",
    "B3",
    "B4",
    "B8",
    "B11",
    "B12",
    "NDVI",
    "NDBI",
    "MNDWI"
]

X_train = train_df[features]

y_train = train_df["Human_Class"]

# =====================================
# TRAIN RF
# =====================================

rf = RandomForestClassifier(
    n_estimators=500,
    random_state=42,
    n_jobs=-1
)

rf.fit(
    X_train,
    y_train
)

print("Human Classifier Trained")

Human Classifier Trained

In [104]:
# =====================================
# PREDICT ALL
# =====================================

X_all = orig[features]

probs = rf.predict_proba(X_all)

pred_class = rf.predict(X_all)

confidence = probs.max(axis=1)

orig["Pred_Class"] = pred_class

orig["Confidence"] = confidence

# =====================================
# FIND DISAGREEMENTS
# =====================================

candidates = orig[
    orig["Pred_Class"]
    !=
    orig["Class"]
].copy()

# =====================================
# HIGH CONFIDENCE ONLY
# =====================================

candidates = candidates[
    candidates["Confidence"] >= 0.95
]

candidates = candidates.sort_values(
    "Confidence",
    ascending=False
)

print(
    "Candidates:",
    len(candidates)
)

print(
    candidates[
        [
            "Original_ID",
            "Class",
            "Pred_Class",
            "Confidence"
        ]
    ].head(20)
)

candidates.to_csv(
    "../data2/Nanjing/07_results/Nanjing_HighConfidence_Disagreements.csv",
    index=False
)

Candidates: 128
      Original_ID  Class  Pred_Class  Confidence
5775         5775      2           1       0.996
3830         3830      1           2       0.990
7873         7873      2           1       0.988
1979         1979      1           2       0.988
2563         2563      1           2       0.986
4179         4179      1           2       0.986
2322         2322      1           2       0.986
7567         7567      2           1       0.984
1785         1785      1           2       0.982
4496         4496      1           2       0.982
2632         2632      1           2       0.980
2823         2823      1           2       0.980
3238         3238      1           2       0.980
1832         1832      1           2       0.978
3144         3144      1           2       0.978
3208         3208      1           2       0.978
2244         2244      1           2       0.978
727           727      1           2       0.978
4898         4898      1           2       0.978
4658         4658      1           2       0.978

In [106]:
import pandas as pd

# =====================================
# PREDICT ALL
# =====================================

X_all = orig[features]

pred_class = rf.predict(X_all)

probs = rf.predict_proba(X_all)

confidence = probs.max(axis=1)

# =====================================
# COPY
# =====================================

cleaned = orig.copy()

mask = (
    (pred_class != cleaned["Class"])
    &
    (confidence >= 0.95)
)

changed = mask.sum()

cleaned.loc[
    mask,
    "Class"
] = pred_class[mask]

print(
    "Automatically relabeled:",
    changed
)

# =====================================
# SAVE
# =====================================

cleaned.to_csv(
    "../data2/Nanjing/05_corrected/Nanjing_HumanClassifier_095.csv",
    index=False
)

print("Saved")

Automatically relabeled: 128
Saved

In [108]:
import pandas as pd

from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

FILE = (
    "../data2/Nanjing/05_corrected/"
    "Nanjing_HumanClassifier_095.csv"
)

features = [
    "B2","B3","B4","B8",
    "B11","B12",
    "NDVI","NDBI","MNDWI"
]

df = pd.read_csv(FILE)

X = df[features]
y = df["Class"]

X_train,X_test,y_train,y_test = train_test_split(
    X,
    y,
    test_size=0.3,
    random_state=42,
    stratify=y
)

rf2 = RandomForestClassifier(
    n_estimators=300,
    random_state=42,
    n_jobs=-1
)

rf2.fit(X_train,y_train)

pred = rf2.predict(X_test)

oa = accuracy_score(
    y_test,
    pred
)

print(
    f"HumanClassifier Pixel OA = {oa:.6f}"
)

HumanClassifier Pixel OA = 0.894444

In [110]:
import pandas as pd

feat = pd.read_csv(
    "../data2/Nanjing/06_3x3/Nanjing_3x3_Features.csv"
)

cleaned = pd.read_csv(
    "../data2/Nanjing/05_corrected/Nanjing_HumanClassifier_095.csv"
)

class_map = cleaned.set_index(
    "Original_ID"
)["Class"]

feat["Class"] = (
    feat["Original_ID"]
    .map(class_map)
)

feat.to_csv(
    "../data2/Nanjing/06_3x3/Nanjing_HumanClassifier_095_3x3.csv",
    index=False
)

print("saved")

saved

In [111]:
import pandas as pd

from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

FILE = (
    "../data2/Nanjing/06_3x3/"
    "Nanjing_HumanClassifier_095_3x3.csv"
)

features = [

    "B2_mean","B2_stdDev",
    "B3_mean","B3_stdDev",
    "B4_mean","B4_stdDev",
    "B8_mean","B8_stdDev",

    "B11_mean","B11_stdDev",
    "B12_mean","B12_stdDev",

    "NDVI_mean","NDVI_stdDev",
    "NDBI_mean","NDBI_stdDev",
    "MNDWI_mean","MNDWI_stdDev"
]

df = pd.read_csv(FILE)

X = df[features]
y = df["Class"]

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.3,
    random_state=42,
    stratify=y
)

rf = RandomForestClassifier(
    n_estimators=300,
    random_state=42,
    n_jobs=-1
)

rf.fit(X_train, y_train)

pred = rf.predict(X_test)

oa = accuracy_score(
    y_test,
    pred
)

print("\n==============================")
print("NANJING HUMAN CLASSIFIER + 3x3")
print("==============================")

print(
    f"OA = {oa:.6f}"
)

==============================
NANJING HUMAN CLASSIFIER + 3x3
==============================
OA = 0.913556

In [113]:
import pandas as pd

ORIGINAL_FILE = "../data2/Nanchang/01_original/Nanchang_WC_Samples_15000.csv"
MANUAL_FILE = "../data2/Nanchang/04_manual/Nanchang_Top150_Manual.csv"

orig = pd.read_csv(ORIGINAL_FILE)
manual = pd.read_csv(MANUAL_FILE)

manual["Human_Class"] = pd.to_numeric(
    manual["Human_Class"],
    errors="coerce"
)

manual = manual[manual["Human_Class"].notna()]

merged = manual.merge(
    orig[["Original_ID","Class"]],
    on="Original_ID"
)

correct = (
    merged["Class"] ==
    merged["Human_Class"]
).sum()

wrong = (
    merged["Class"] !=
    merged["Human_Class"]
).sum()

print("Margin Correct =", correct)
print("Margin Wrong =", wrong)
print("Margin Accuracy =", correct/len(merged))

Margin Correct = 102
Margin Wrong = 48
Margin Accuracy = 0.68

In [115]:
import pandas as pd

ORIGINAL_FILE = "../data2/Nanchang/01_original/Nanchang_WC_Samples_15000.csv"
MANUAL_FILE = "../data2/Nanchang/04_manual/Nanchang_BAMS150_Manual.csv"

orig = pd.read_csv(ORIGINAL_FILE)
manual = pd.read_csv(MANUAL_FILE)

manual["Human_Class"] = pd.to_numeric(
    manual["Human_Class"],
    errors="coerce"
)

manual = manual[manual["Human_Class"].notna()]

merged = manual.merge(
    orig[["Original_ID","Class"]],
    on="Original_ID"
)

correct = (
    merged["Class"] ==
    merged["Human_Class"]
).sum()

wrong = (
    merged["Class"] !=
    merged["Human_Class"]
).sum()

print("BAMS Correct =", correct)
print("BAMS Wrong =", wrong)
print("BAMS Accuracy =", correct/len(merged))

BAMS Correct = 83
BAMS Wrong = 67
BAMS Accuracy = 0.5533333333333333

In [119]:
import pandas as pd

from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

# FILE = "../data2/Nanchang/01_original/Nanchang_WC_Samples_15000.csv"
# FILE = "../data2/Nanchang/05_corrected/Nanchang_BAMS_Corrected_15000.csv"
FILE = "../data2/Nanchang/06_3x3/Nanchang_3x3_Features_Corrected.csv"# 
features = [
    "B2","B3","B4","B8",
    "B11","B12",
    "NDVI","NDBI","MNDWI"
]

df = pd.read_csv(FILE)

X = df[features]
y = df["Class"]

X_train,X_test,y_train,y_test = train_test_split(
    X,y,
    test_size=0.3,
    random_state=42,
    stratify=y
)

rf = RandomForestClassifier(
    n_estimators=300,
    random_state=42,
    n_jobs=-1
)

rf.fit(X_train,y_train)

pred = rf.predict(X_test)

oa = accuracy_score(y_test,pred)

print("Original Pixel OA =", oa)

KeyError: "None of [Index(['B2', 'B3', 'B4', 'B8', 'B11', 'B12', 'NDVI', 'NDBI', 'MNDWI'], dtype='str')] are in the [columns]"

In [122]:
import pandas as pd

from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

FILE = (
    "../data2/Nanchang/05_corrected/"
    "Nanchang_BAMS_Corrected_15000.csv"
)

features = [
    "B2",
    "B3",
    "B4",
    "B8",
    "B11",
    "B12",
    "NDVI",
    "NDBI",
    "MNDWI"
]

df = pd.read_csv(FILE)

X = df[features]
y = df["Class"]

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.3,
    random_state=42,
    stratify=y
)

rf = RandomForestClassifier(
    n_estimators=300,
    random_state=42,
    n_jobs=-1
)

rf.fit(X_train, y_train)

pred = rf.predict(X_test)

oa = accuracy_score(y_test, pred)

print("\n==============================")
print("NANCHANG BAMS + PIXEL")
print("==============================")

print(f"OA = {oa:.6f}")

==============================
NANCHANG BAMS + PIXEL
==============================
OA = 0.895778

In [123]:
import pandas as pd

from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

FILE = (
    "../data2/Nanchang/06_3x3/"
    "Nanchang_3x3_Features_Corrected.csv"
)

features = [

    "B2_mean","B2_stdDev",
    "B3_mean","B3_stdDev",
    "B4_mean","B4_stdDev",
    "B8_mean","B8_stdDev",

    "B11_mean","B11_stdDev",
    "B12_mean","B12_stdDev",

    "NDVI_mean","NDVI_stdDev",
    "NDBI_mean","NDBI_stdDev",
    "MNDWI_mean","MNDWI_stdDev"
]

df = pd.read_csv(FILE)

X = df[features]
y = df["Class"]

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.3,
    random_state=42,
    stratify=y
)

rf = RandomForestClassifier(
    n_estimators=300,
    random_state=42,
    n_jobs=-1
)

rf.fit(X_train, y_train)

pred = rf.predict(X_test)

oa = accuracy_score(y_test, pred)

print("\n==============================")
print("NANCHANG MARGIN + 3x3")
print("==============================")

print(f"OA = {oa:.6f}")

==============================
NANCHANG MARGIN + 3x3
==============================
OA = 0.910000

In [126]:
import pandas as pd

from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

FILE = "../data2/Nanchang/06_3x3/Nanchang_3x3_Features.csv"

features = [

    "B2_mean","B2_stdDev",
    "B3_mean","B3_stdDev",
    "B4_mean","B4_stdDev",
    "B8_mean","B8_stdDev",

    "B11_mean","B11_stdDev",
    "B12_mean","B12_stdDev",

    "NDVI_mean","NDVI_stdDev",
    "NDBI_mean","NDBI_stdDev",
    "MNDWI_mean","MNDWI_stdDev"
]

df = pd.read_csv(FILE)

X = df[features]
y = df["Class"]

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.3,
    random_state=42,
    stratify=y
)

rf = RandomForestClassifier(
    n_estimators=300,
    random_state=42,
    n_jobs=-1
)

rf.fit(X_train, y_train)

pred = rf.predict(X_test)

oa = accuracy_score(y_test, pred)

print("\n==============================")
print("NANCHANG BAMS + 3x3")
print("==============================")

print(f"OA = {oa:.6f}")

==============================
NANCHANG BAMS + 3x3
==============================
OA = 0.914444

In [127]:
import pandas as pd

from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

FILE = (
    "../data2/Nanchang/06_3x3/"
    "Nanchang_3x3_Features.csv"
)

features = [

    "B2_mean","B2_stdDev",
    "B3_mean","B3_stdDev",
    "B4_mean","B4_stdDev",
    "B8_mean","B8_stdDev",

    "B11_mean","B11_stdDev",
    "B12_mean","B12_stdDev",

    "NDVI_mean","NDVI_stdDev",
    "NDBI_mean","NDBI_stdDev",
    "MNDWI_mean","MNDWI_stdDev"
]

df = pd.read_csv(FILE)

X = df[features]
y = df["Class"]

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.3,
    random_state=42,
    stratify=y
)

rf = RandomForestClassifier(
    n_estimators=300,
    random_state=42,
    n_jobs=-1
)

rf.fit(X_train, y_train)

pred = rf.predict(X_test)

oa = accuracy_score(
    y_test,
    pred
)

print("\n==============================")
print("NANCHANG ORIGINAL + 3x3")
print("==============================")

print(
    f"OA = {oa:.6f}"
)

==============================
NANCHANG ORIGINAL + 3x3
==============================
OA = 0.914444

In [128]:
import pandas as pd

from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

FILE = (
    "../data2/Changsha/01_original/"
    "Changsha_WC_Samples_15000.csv"
)

features = [
    "B2","B3","B4","B8",
    "B11","B12",
    "NDVI","NDBI","MNDWI"
]

df = pd.read_csv(FILE)

X = df[features]
y = df["Class"]

X_train, X_test, y_train, y_test = train_test_split(
    X, y,
    test_size=0.3,
    random_state=42,
    stratify=y
)

rf = RandomForestClassifier(
    n_estimators=300,
    random_state=42,
    n_jobs=-1
)

rf.fit(X_train, y_train)

pred = rf.predict(X_test)

oa = accuracy_score(y_test, pred)

print("\n==============================")
print("CHANGSHA ORIGINAL + PIXEL")
print("==============================")
print(f"OA = {oa:.6f}")

==============================
CHANGSHA ORIGINAL + PIXEL
==============================
OA = 0.922000

In [129]:
import pandas as pd

from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

FILE = (
    "../data2/Changsha/06_3x3/"
    "Changsha_3x3_Features.csv"
)

features = [

    "B2_mean","B2_stdDev",
    "B3_mean","B3_stdDev",
    "B4_mean","B4_stdDev",
    "B8_mean","B8_stdDev",

    "B11_mean","B11_stdDev",
    "B12_mean","B12_stdDev",

    "NDVI_mean","NDVI_stdDev",
    "NDBI_mean","NDBI_stdDev",
    "MNDWI_mean","MNDWI_stdDev"
]

df = pd.read_csv(FILE)

X = df[features]
y = df["Class"]

X_train, X_test, y_train, y_test = train_test_split(
    X, y,
    test_size=0.3,
    random_state=42,
    stratify=y
)

rf = RandomForestClassifier(
    n_estimators=300,
    random_state=42,
    n_jobs=-1
)

rf.fit(X_train, y_train)

pred = rf.predict(X_test)

oa = accuracy_score(y_test, pred)

print("\n==============================")
print("CHANGSHA ORIGINAL + 3x3")
print("==============================")
print(f"OA = {oa:.6f}")

==============================
CHANGSHA ORIGINAL + 3x3
==============================
OA = 0.928222

In [130]:
import pandas as pd

from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

ORIGINAL_FILE = (
    "../data2/Changsha/01_original/"
    "Changsha_WC_Samples_15000.csv"
)

MANUAL_FILE = (
    "../data2/Changsha/04_manual/"
    "Changsha_BAMS150_Manual.csv"
)

CORRECTED_FILE = (
    "../data2/Changsha/05_corrected/"
    "Changsha_BAMS_Corrected_15000.csv"
)

df = pd.read_csv(ORIGINAL_FILE)
manual = pd.read_csv(MANUAL_FILE)

changes = 0

for _, row in manual.iterrows():

    if pd.isna(row["Human_Class"]):
        continue

    oid = int(row["Original_ID"])
    human = int(row["Human_Class"])

    mask = df["Original_ID"] == oid

    old_class = df.loc[
        mask,
        "Class"
    ].iloc[0]

    if old_class != human:

        df.loc[
            mask,
            "Class"
        ] = human

        changes += 1

df.to_csv(
    CORRECTED_FILE,
    index=False
)

print("Labels changed:", changes)

features = [
    "B2","B3","B4","B8",
    "B11","B12",
    "NDVI","NDBI","MNDWI"
]

X = df[features]
y = df["Class"]

X_train, X_test, y_train, y_test = train_test_split(
    X, y,
    test_size=0.3,
    random_state=42,
    stratify=y
)

rf = RandomForestClassifier(
    n_estimators=300,
    random_state=42,
    n_jobs=-1
)

rf.fit(X_train, y_train)

pred = rf.predict(X_test)

oa = accuracy_score(y_test, pred)

print("\n==============================")
print("CHANGSHA BAMS + PIXEL")
print("==============================")
print(f"OA = {oa:.6f}")

Labels changed: 79

==============================
CHANGSHA BAMS + PIXEL
==============================
OA = 0.930667

In [131]:
import pandas as pd

from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

FEATURE_FILE = (
    "../data2/Changsha/06_3x3/"
    "Changsha_3x3_Features.csv"
)

MANUAL_FILE = (
    "../data2/Changsha/04_manual/"
    "Changsha_BAMS150_Manual.csv"
)

CORRECTED_FILE = (
    "../data2/Changsha/06_3x3/"
    "Changsha_BAMS_Corrected_3x3.csv"
)

df = pd.read_csv(FEATURE_FILE)
manual = pd.read_csv(MANUAL_FILE)

changes = 0

for _, row in manual.iterrows():

    if pd.isna(row["Human_Class"]):
        continue

    oid = int(row["Original_ID"])
    human = int(row["Human_Class"])

    mask = (
        df["Original_ID"] == oid
    )

    old_class = df.loc[
        mask,
        "Class"
    ].iloc[0]

    if old_class != human:

        df.loc[
            mask,
            "Class"
        ] = human

        changes += 1

df.to_csv(
    CORRECTED_FILE,
    index=False
)

print("Labels changed:", changes)

features = [

    "B2_mean","B2_stdDev",
    "B3_mean","B3_stdDev",
    "B4_mean","B4_stdDev",
    "B8_mean","B8_stdDev",

    "B11_mean","B11_stdDev",
    "B12_mean","B12_stdDev",

    "NDVI_mean","NDVI_stdDev",
    "NDBI_mean","NDBI_stdDev",
    "MNDWI_mean","MNDWI_stdDev"
]

X = df[features]
y = df["Class"]

X_train, X_test, y_train, y_test = train_test_split(
    X, y,
    test_size=0.3,
    random_state=42,
    stratify=y
)

rf = RandomForestClassifier(
    n_estimators=300,
    random_state=42,
    n_jobs=-1
)

rf.fit(X_train, y_train)

pred = rf.predict(X_test)

oa = accuracy_score(y_test, pred)

print("\n==============================")
print("CHANGSHA BAMS + 3x3")
print("==============================")
print(f"OA = {oa:.6f}")

Labels changed: 79

==============================
CHANGSHA BAMS + 3x3
==============================
OA = 0.929111

In [136]:
import pandas as pd

from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

ORIGINAL_FILE = (
    "../data2/Changsha/01_original/"
    "Changsha_WC_Samples_15000.csv"
)

MANUAL_FILE = (
    "../data2/Changsha/04_manual/"
    "Changsha_Top150_Manual.csv"
)

CORRECTED_FILE = (
    "../data2/Changsha/05_corrected/"
    "Changsha_Corrected_15000.csv"
)

df = pd.read_csv(ORIGINAL_FILE)
manual = pd.read_csv(MANUAL_FILE)

changes = 0

for _, row in manual.iterrows():

    if pd.isna(row["Human_Class"]):
        continue

    oid = int(row["Original_ID"])
    human = int(row["Human_Class"])

    mask = df["Original_ID"] == oid

    old_class = df.loc[mask, "Class"].iloc[0]

    if old_class != human:

        df.loc[mask, "Class"] = human
        changes += 1

df.to_csv(
    CORRECTED_FILE,
    index=False
)

print("Labels changed:", changes)

features = [
    "B2","B3","B4","B8",
    "B11","B12",
    "NDVI","NDBI","MNDWI"
]

X = df[features]
y = df["Class"]

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.3,
    random_state=42,
    stratify=y
)

rf = RandomForestClassifier(
    n_estimators=300,
    random_state=42,
    n_jobs=-1
)

rf.fit(X_train, y_train)

pred = rf.predict(X_test)

oa = accuracy_score(y_test, pred)

print("\n==============================")
print("CHANGSHA MARGIN + PIXEL")
print("==============================")
print(f"OA = {oa:.6f}")

Labels changed: 52

==============================
CHANGSHA MARGIN + PIXEL
==============================
OA = 0.928667

In [135]:
import pandas as pd

from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

FEATURE_FILE = (
    "../data2/Changsha/06_3x3/"
    "Changsha_3x3_Features.csv"
)

MANUAL_FILE = (
    "../data2/Changsha/04_manual/"
    "Changsha_Top150_Manual.csv"
)

CORRECTED_FILE = (
    "../data2/Changsha/06_3x3/"
    "Changsha_3x3_Features_Corrected.csv"
)

df = pd.read_csv(FEATURE_FILE)
manual = pd.read_csv(MANUAL_FILE)

changes = 0

for _, row in manual.iterrows():

    if pd.isna(row["Human_Class"]):
        continue

    oid = int(row["Original_ID"])
    human = int(row["Human_Class"])

    mask = df["Original_ID"] == oid

    old_class = df.loc[mask, "Class"].iloc[0]

    if old_class != human:

        df.loc[mask, "Class"] = human
        changes += 1

df.to_csv(
    CORRECTED_FILE,
    index=False
)

print("Labels changed:", changes)

features = [

    "B2_mean","B2_stdDev",
    "B3_mean","B3_stdDev",
    "B4_mean","B4_stdDev",
    "B8_mean","B8_stdDev",

    "B11_mean","B11_stdDev",
    "B12_mean","B12_stdDev",

    "NDVI_mean","NDVI_stdDev",
    "NDBI_mean","NDBI_stdDev",
    "MNDWI_mean","MNDWI_stdDev"
]

X = df[features]
y = df["Class"]

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.3,
    random_state=42,
    stratify=y
)

rf = RandomForestClassifier(
    n_estimators=300,
    random_state=42,
    n_jobs=-1
)

rf.fit(X_train, y_train)

pred = rf.predict(X_test)

oa = accuracy_score(y_test, pred)

print("\n==============================")
print("CHANGSHA MARGIN + 3x3")
print("==============================")
print(f"OA = {oa:.6f}")

Labels changed: 52

==============================
CHANGSHA MARGIN + 3x3
==============================
OA = 0.935778