In [2]:
import pandas as pd

df = pd.read_csv(
    "../data/Wuhan_WC_Samples_15000.csv"
)

df.head()

,system:index,B11,B12,B2,B3,B4,B8,Class,MNDWI,NDBI,NDVI,lat,lon,.geo
0,0,2143.75,2064.0,1438.0,1500.333333,1608.0,2201.0,1,-0.176565,-0.013177,0.155684,30.566660,114.163970,"{""geodesic"":false,""type"":""Point"",""coordinates""..."
1,1,2095.00,2041.0,822.0,886.000000,1216.0,1592.0,1,-0.405569,0.136425,0.133903,30.605736,114.333572,"{""geodesic"":false,""type"":""Point"",""coordinates""..."
2,2,2648.00,2261.5,780.5,1003.000000,1096.0,2199.0,1,-0.450562,0.092635,0.334750,30.479883,113.827820,"{""geodesic"":false,""type"":""Point"",""coordinates""..."
3,3,1526.00,1379.0,930.0,1140.000000,1256.0,1704.0,1,-0.144786,-0.055108,0.151351,30.769769,114.274283,"{""geodesic"":false,""type"":""Point"",""coordinates""..."
4,4,2255.50,1930.5,732.5,995.000000,1414.0,2376.0,1,-0.387786,-0.026017,0.253826,30.841904,114.934724,"{""geodesic"":false,""type"":""Point"",""coordinates""..."

In [3]:
df["Class"].value_counts()

Class
1    5000
2    5000
3    5000
Name: count, dtype: int64

In [4]:
features = [
    "B2",
    "B3",
    "B4",
    "B8",
    "B11",
    "B12",
    "NDVI",
    "NDBI",
    "MNDWI"
]

X = df[features]
y = df["Class"]

In [5]:
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.3,
    random_state=42,
    stratify=y
)

rf = RandomForestClassifier(
    n_estimators=100,
    random_state=42,
    n_jobs=-1
)

rf.fit(X_train, y_train)

RandomForestClassifier(n_jobs=-1, random_state=42)

In [9]:
import numpy as np
prob = rf.predict_proba(X_test)

sorted_prob = np.sort(
    prob,
    axis=1
)

margin = (
    sorted_prob[:, -1]
    -
    sorted_prob[:, -2]
)

hard_idx = np.argsort(margin)

In [10]:
import numpy as np

prob = rf.predict_proba(X_test)

sorted_prob = np.sort(
    prob,
    axis=1
)

margin = (
    sorted_prob[:, -1]
    -
    sorted_prob[:, -2]
)

hard_idx = np.argsort(margin)

print("Top 10 margins:")
print(margin[hard_idx[:10]])

Top 10 margins:
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]

In [11]:
hard_samples = df.loc[
    X_test.iloc[hard_idx[:100]].index,
    ['lon','lat','Class']
].copy()

hard_samples['margin'] = (
    margin[hard_idx[:100]]
)

hard_samples.to_csv(
    "../data/Wuhan_top100.csv",
    index=False
)

hard_samples.head()

             lon        lat  Class  margin
9045  113.968407  30.331121      2     0.0
6215  113.877587  30.361754      2     0.0
4063  114.284344  30.297884      1     0.0
5950  113.961490  30.312796      2     0.0
762   114.272486  30.983927      1     0.0

In [2]:
print(df.shape)

print(df.columns.tolist())

(15000, 14)
['system:index', 'B11', 'B12', 'B2', 'B3', 'B4', 'B8', 'Class', 'MNDWI', 'NDBI', 'NDVI', 'lat', 'lon', '.geo']

In [3]:
df['Class'].value_counts()

Class
1    5000
2    5000
3    5000
Name: count, dtype: int64

In [4]:
df.isnull().sum()

system:index    0
B11             0
B12             0
B2              0
B3              0
B4              0
B8              0
Class           0
MNDWI           0
NDBI            0
NDVI            0
lat             0
lon             0
.geo            0
dtype: int64

In [5]:
print(df.shape)
print(df.columns.tolist())
df['Class'].value_counts()

(15000, 14)
['system:index', 'B11', 'B12', 'B2', 'B3', 'B4', 'B8', 'Class', 'MNDWI', 'NDBI', 'NDVI', 'lat', 'lon', '.geo']

Class
1    5000
2    5000
3    5000
Name: count, dtype: int64

In [9]:
import pandas as pd

from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score

df = pd.read_csv(
    "../data/Nanchang_WC_Samples_15000.csv"
)

features = [
    'B2','B3','B4',
    'B8','B11','B12',
    'NDVI','NDBI','MNDWI'
]

X = df[features]
y = df['Class']

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.3,
    random_state=42,
    stratify=y
)

rf = RandomForestClassifier(
    n_estimators=100,
    random_state=42
)

rf.fit(X_train, y_train)

pred = rf.predict(X_test)

print(
    "OA:",
    accuracy_score(y_test, pred)
)

OA: 0.898

In [10]:
import numpy as np

prob = rf.predict_proba(X_test)

prob[:5]

array([[0.64, 0.36, 0.  ],
       [0.18, 0.82, 0.  ],
       [0.53, 0.47, 0.  ],
       [0.  , 0.03, 0.97],
       [0.  , 0.  , 1.  ]])

In [11]:
sorted_prob = np.sort(
    prob,
    axis=1
)

margin = (
    sorted_prob[:, -1]
    -
    sorted_prob[:, -2]
)

margin[:10]

array([0.28, 0.64, 0.06, 0.94, 1.  , 0.96, 0.32, 0.85, 0.94, 0.98])

In [12]:
hard_idx = np.argsort(margin)

hard_idx[:10]

array([2101, 2580,  831, 2715,  708,  319,  579, 2105, 2125, 2204])

In [13]:
hard_samples = (
    X_test.iloc[hard_idx[:100]]
)

hard_samples.head()

,B2,B3,B4,B8,B11,B12,NDVI,NDBI,MNDWI
9342,894.000000,1365.5,1415.000000,2320.0,1872.0,1282.0,0.242303,-0.106870,-0.156448
10890,504.500000,794.5,636.000000,2422.5,1573.5,1100.5,0.584110,-0.212462,-0.328970
12612,670.000000,999.0,946.000000,1923.0,1572.0,1063.0,0.340537,-0.100429,-0.222870
9999,785.666667,1147.0,1125.333333,2568.0,2403.0,1787.0,0.390614,-0.033193,-0.353803
11843,1587.000000,2014.0,2425.000000,2826.0,3868.0,3461.5,0.076366,0.155662,-0.315199

In [14]:
hard_samples = df.loc[
    X_test.iloc[hard_idx[:100]].index,
    ['lon','lat','Class']
]

hard_samples.head()

              lon        lat  Class
9342   115.980633  29.024342      2
10890  116.428982  28.670586      3
12612  115.906522  28.785840      3
9999   115.987819  28.409356      2
11843  116.098402  28.513560      3

In [16]:
from pathlib import Path

out = Path("../outputs")
out.mkdir(parents=True, exist_ok=True)

hard_samples.to_csv(
    out / "top100_uncertain.csv",
    index=False
)
print("saved:", out.resolve() / "top100_uncertain.csv")

saved: /Users/alex/Projects/gee-project/outputs/top100_uncertain.csv

In [17]:
prob[:5]

margin[:20]

hard_samples.head()

              lon        lat  Class
9342   115.980633  29.024342      2
10890  116.428982  28.670586      3
12612  115.906522  28.785840      3
9999   115.987819  28.409356      2
11843  116.098402  28.513560      3

In [18]:
print("Probability:")
print(prob[:5])

print("\nMargin:")
print(margin[:20])

print("\nHard Samples:")
hard_samples.head()

Probability:
[[0.64 0.36 0.  ]
 [0.18 0.82 0.  ]
 [0.53 0.47 0.  ]
 [0.   0.03 0.97]
 [0.   0.   1.  ]]

Margin:
[0.28 0.64 0.06 0.94 1.   0.96 0.32 0.85 0.94 0.98 0.73 0.96 0.91 0.64
 0.98 0.88 1.   1.   0.89 0.68]

Hard Samples:

              lon        lat  Class
9342   115.980633  29.024342      2
10890  116.428982  28.670586      3
12612  115.906522  28.785840      3
9999   115.987819  28.409356      2
11843  116.098402  28.513560      3

In [19]:
hard_samples = df.loc[
    X_test.iloc[hard_idx[:100]].index,
    ['lon', 'lat', 'Class']
].copy()

hard_samples['margin'] = margin[
    hard_idx[:100]
]

hard_samples.to_csv(
    "../data/top100_uncertain_samples.csv",
    index=False
)

hard_samples.head()

              lon        lat  Class  margin
9342   115.980633  29.024342      2     0.0
10890  116.428982  28.670586      3     0.0
12612  115.906522  28.785840      3     0.0
9999   115.987819  28.409356      2     0.0
11843  116.098402  28.513560      3     0.0

In [20]:
len(hard_samples)

100

In [21]:
hard_samples["margin"].describe()

count    100.000000
mean       0.037000
std        0.021858
min        0.000000
25%        0.020000
50%        0.040000
75%        0.060000
max        0.070000
Name: margin, dtype: float64

In [22]:
hard_samples.to_string()

'              lon        lat  Class  margin\n9342   115.980633  29.024342      2    0.00\n10890  116.428982  28.670586      3    0.00\n12612  115.906522  28.785840      3    0.00\n9999   115.987819  28.409356      2    0.00\n11843  116.098402  28.513560      3    0.00\n5526   115.892957  28.462805      2    0.00\n11210  116.305104  28.714154      3    0.00\n3087   115.541357  28.740475      1    0.01\n11499  115.812468  28.359319      3    0.01\n4196   116.308877  28.272902      1    0.01\n9244   115.945868  28.572400      2    0.01\n4125   116.169369  28.233465      1    0.01\n14568  116.218417  29.063958      3    0.01\n7333   115.899964  28.807758      2    0.01\n11773  116.035520  28.687294      3    0.01\n11824  115.980813  28.842613      3    0.01\n5797   116.236293  28.607254      2    0.01\n9155   115.793244  28.405493      2    0.01\n6553   116.310854  29.053088      2    0.01\n10443  116.023033  29.071683      3    0.02\n6182   116.133796  28.990835      2    0.02\n14253  116.167842  28.600787      3    0.02\n14264  115.902300  28.944572      3    0.02\n1383   115.852264  28.773173      1    0.02\n9516   116.130831  28.300210      2    0.02\n5365   115.963295  28.466578      2    0.02\n14170  116.181047  29.078421      3    0.02\n9215   116.185539  28.476639      2    0.02\n12633  116.287138  29.110670      3    0.02\n4645   115.992401  28.594678      1    0.02\n8567   115.889184  28.749548      2    0.02\n3373   115.897718  28.591803      1    0.02\n8414   116.410836  29.001884      2    0.02\n7988   116.343552  28.963077      2    0.02\n1521   115.784351  28.446726      1    0.02\n4903   116.085197  28.794284      1    0.02\n1708   115.796299  28.563417      1    0.03\n1719   115.779231  28.640312      1    0.03\n14585  116.243660  29.125043      3    0.03\n8432   116.021776  28.422022      2    0.03\n10386  116.099211  28.510596      3    0.03\n7745   115.551148  28.427591      2    0.03\n5215   116.340678  28.937475      2    0.03\n8420   116.261985  28.357882      2    0.03\n14088  115.482158  28.784851      3    0.03\n10729  116.245366  28.738229      3    0.03\n6893   116.128136  28.844410      2    0.03\n14498  116.111607  28.244605      3    0.03\n7618   115.681494  28.904507      2    0.04\n6371   116.096066  28.311978      2    0.04\n14447  116.237282  29.109413      3    0.04\n2563   115.722098  28.670316      1    0.04\n8663   116.249409  28.534940      2    0.04\n7432   116.035700  28.850788      2    0.04\n12564  116.405356  29.005837      3    0.04\n5615   115.893856  28.486701      2    0.04\n4728   116.296031  28.374501      1    0.04\n8214   115.595256  28.794194      2    0.04\n7381   116.311842  28.963077      2    0.04\n8534   115.975692  28.528652      2    0.05\n6951   116.233958  28.192412      2    0.05\n12768  115.579445  28.975384      3    0.05\n7879   116.068578  28.668160      2    0.05\n4379   115.888556  28.732300      1    0.05\n10265  116.010277  28.588570      3    0.05\n3016   116.119692  28.869473      1    0.05\n7511   116.127867  28.720622      2    0.05\n11912  116.118345  28.634384      3    0.05\n10940  115.832321  28.886271      3    0.05\n4146   115.788034  28.614531      1    0.05\n2039   115.811750  28.688372      1    0.05\n3472   115.667211  28.486162      1    0.05\n4591   116.068129  28.353750      1    0.05\n3812   116.002642  28.963347      1    0.06\n7263   116.006594  28.764819      2    0.06\n8322   116.245456  28.478077      2    0.06\n771    115.815612  28.627467      1    0.06\n13540  116.087443  28.489845      3    0.06\n5627   115.980902  28.564045      2    0.06\n10827  116.032466  28.749997      3    0.06\n9407   115.987280  28.442503      2    0.06\n6001   115.838070  28.722778      2    0.06\n4775   115.909307  28.647409      1    0.06\n1369   116.108373  28.520387      1    0.06\n7014   116.402212  28.951309      2    0.06\n661    115.909666  28.817820      1    0.06\n8699   116.218507  28.930289      2    0.06\n11463  116.390894  28.714513      3    0.06\n2814   115.894844  28.535479      1    0.07\n1291   115.727578  28.622526      1    0.07\n14541  115.751563  28.377465      3    0.07\n9085   116.166494  29.098813      2    0.07\n1301   115.550070  28.841445      1    0.07\n4079   116.109092  28.850339      1    0.07\n4007   116.402122  28.313685      1    0.07\n3772   115.745993  28.680108      1    0.07\n9954   115.533901  28.735354      2    0.07\n6124   116.273933  28.992542      2    0.07\n3769   116.105050  28.655314      1    0.07\n1445   116.328461  28.692145      1    0.07'

In [23]:
human_labels = {
  1:2, 2:2, 3:2, 4:2, 5:2,
  6:2, 7:3, 8:1, 9:2, 10:2,
  11:2, 12:1, 13:3, 14:2, 15:2,
  16:3, 17:3, 18:2, 19:3, 20:3,

  21:2,22:2,23:3,24:1,25:2,
  26:2,27:3,28:2,29:3,30:2,
  31:2,32:1,33:3,34:3,35:2,
  36:2,37:1,38:2,39:3,40:2,

  41:2,42:2,43:3,44:2,45:2,
  46:2,47:2,48:2,49:2,50:2,
  51:3,52:1,53:2,54:2,55:3,
  56:2,57:2,58:3,59:3,60:2,

  61:2,62:3,63:1,64:2,65:3,
  66:3,67:3,68:3,69:3,70:1,
  71:2,72:2,73:2,74:3,75:3,
  76:2,77:1,78:3,79:3,80:3,

  81:2,82:2,83:1,84:2,85:3,
  86:2,87:3,88:3,89:1,90:1,
  91:2,92:3,93:3,94:2,95:2,
  96:1,97:2,98:3,99:2,100:2
}

In [24]:
hard_samples = hard_samples.reset_index(drop=True)

hard_samples["PointID"] = range(
    1,
    len(hard_samples)+1
)

hard_samples["WC_Class"] = (
    hard_samples["Class"]
)

hard_samples["Human_Class"] = (
    hard_samples["PointID"]
    .map(human_labels)
)

top100_corrected = hard_samples[
    [
        "PointID",
        "lon",
        "lat",
        "WC_Class",
        "Human_Class",
        "margin"
    ]
]

top100_corrected.head()

   PointID         lon        lat  WC_Class  Human_Class  margin
0        1  115.980633  29.024342         2            2     0.0
1        2  116.428982  28.670586         3            2     0.0
2        3  115.906522  28.785840         3            2     0.0
3        4  115.987819  28.409356         2            2     0.0
4        5  116.098402  28.513560         3            2     0.0

In [25]:
top100_corrected.to_csv(
    "../data/top100_corrected.csv",
    index=False
)

print(
    "Saved top100_corrected.csv"
)

Saved top100_corrected.csv

In [26]:
top100_corrected.shape

(100, 6)

In [27]:
top100_corrected.head()

   PointID         lon        lat  WC_Class  Human_Class  margin
0        1  115.980633  29.024342         2            2     0.0
1        2  116.428982  28.670586         3            2     0.0
2        3  115.906522  28.785840         3            2     0.0
3        4  115.987819  28.409356         2            2     0.0
4        5  116.098402  28.513560         3            2     0.0

In [28]:
from sklearn.metrics import (
    confusion_matrix,
    classification_report,
    accuracy_score
)

y_true = top100_corrected["Human_Class"]

y_pred = top100_corrected["WC_Class"]

print(
    "WC Accuracy on Top100 =",
    accuracy_score(y_true, y_pred)
)

print(
    confusion_matrix(
        y_true,
        y_pred
    )
)

print(
    classification_report(
        y_true,
        y_pred
    )
)

WC Accuracy on Top100 = 0.55
[[12  1  0]
 [16 26 11]
 [ 3 14 17]]
              precision    recall  f1-score   support

           1       0.39      0.92      0.55        13
           2       0.63      0.49      0.55        53
           3       0.61      0.50      0.55        34

    accuracy                           0.55       100
   macro avg       0.54      0.64      0.55       100
weighted avg       0.59      0.55      0.55       100

In [29]:
wc = pd.read_csv(
    "../data/Nanchang_WC_Samples_15000.csv"
)

corrected = pd.read_csv(
    "../data/top100_corrected.csv"
)

print(wc.shape)
print(corrected.shape)

(15000, 14)
(100, 6)

In [30]:
wc = wc.reset_index(drop=True)

wc["PointID"] = range(
    1,
    len(wc)+1
)

In [31]:
active_df = wc.copy()

In [32]:
human_map = dict(
    zip(
        corrected["PointID"],
        corrected["Human_Class"]
    )
)

In [33]:
for pid, label in human_map.items():
    active_df.loc[
        active_df["PointID"] == pid,
        "Class"
    ] = label

In [34]:
print(
    "Updated Samples:",
    len(human_map)
)

Updated Samples: 100

In [35]:
features = [
    'B2',
    'B3',
    'B4',
    'B8',
    'B11',
    'B12',
    'NDVI',
    'NDBI',
    'MNDWI'
]

X = active_df[features]

y = active_df["Class"]

In [36]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.3,
    random_state=42,
    stratify=y
)

In [37]:
from sklearn.ensemble import RandomForestClassifier

rf_active = RandomForestClassifier(
    n_estimators=100,
    random_state=42,
    n_jobs=-1
)

rf_active.fit(
    X_train,
    y_train
)

RandomForestClassifier(n_jobs=-1, random_state=42)

In [39]:
rf_active.feature_importances_

array([0.09215803, 0.06232907, 0.04316367, 0.12379318, 0.14305907,
       0.15295138, 0.14470378, 0.05571514, 0.18212668])

In [40]:
from sklearn.metrics import cohen_kappa_score

SyntaxError: invalid syntax (2649557973.py, line 1)

In [38]:
from sklearn.metrics import (
    accuracy_score,
    confusion_matrix,
    classification_report
)

pred_active = rf_active.predict(
    X_test
)

oa_active = accuracy_score(
    y_test,
    pred_active
)

print(
    "Active-Rule OA =",
    oa_active
)

print(
    confusion_matrix(
        y_test,
        pred_active
    )
)

print(
    classification_report(
        y_test,
        pred_active
    )
)

Active-Rule OA = 0.9057777777777778
[[1383   82    9]
 [ 128 1279  109]
 [  40   56 1414]]
              precision    recall  f1-score   support

           1       0.89      0.94      0.91      1474
           2       0.90      0.84      0.87      1516
           3       0.92      0.94      0.93      1510

    accuracy                           0.91      4500
   macro avg       0.91      0.91      0.91      4500
weighted avg       0.91      0.91      0.91      4500

In [43]:
from sklearn.metrics import (
    accuracy_score,
    cohen_kappa_score
)

# ======================
# Baseline
# pred 来自：
# pred = rf.predict(X_test)
# ======================

baseline_oa = accuracy_score(
    y_test,
    pred
)

baseline_kappa = cohen_kappa_score(
    y_test,
    pred
)

# ======================
# Active-Rule
# pred_active 来自：
# pred_active = rf_active.predict(X_test)
# ======================

active_oa = accuracy_score(
    y_test,
    pred_active
)

active_kappa = cohen_kappa_score(
    y_test,
    pred_active
)

# ======================
# Print Results
# ======================

print("========== Baseline ==========")
print(f"OA     = {baseline_oa:.4f}")
print(f"Kappa  = {baseline_kappa:.4f}")

print("\n========== Active-Rule ==========")
print(f"OA     = {active_oa:.4f}")
print(f"Kappa  = {active_kappa:.4f}")

print("\n========== Improvement ==========")
print(f"OA Gain       = {active_oa - baseline_oa:.4f}")
print(f"Kappa Gain    = {active_kappa - baseline_kappa:.4f}")

print("\n========== Percentage ==========")
print(f"OA Gain (%)    = {(active_oa - baseline_oa)*100:.2f}%")
print(f"Kappa Gain (%) = {(active_kappa - baseline_kappa)*100:.2f}%")

========== Baseline ==========
OA     = 0.3327
Kappa  = -0.0007

========== Active-Rule ==========
OA     = 0.9058
Kappa  = 0.8587

========== Improvement ==========
OA Gain       = 0.5731
Kappa Gain    = 0.8594

========== Percentage ==========
OA Gain (%)    = 57.31%
Kappa Gain (%) = 85.94%

In [44]:
pred

array([1, 2, 1, ..., 1, 1, 2], shape=(4500,))

In [45]:
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import (
    accuracy_score,
    cohen_kappa_score
)

# Baseline Dataset
X_base = df[features]
y_base = df["Class"]

Xb_train, Xb_test, yb_train, yb_test = train_test_split(
    X_base,
    y_base,
    test_size=0.3,
    random_state=42,
    stratify=y_base
)

rf_base = RandomForestClassifier(
    n_estimators=100,
    random_state=42,
    n_jobs=-1
)

rf_base.fit(Xb_train, yb_train)

pred_base = rf_base.predict(Xb_test)

baseline_oa = accuracy_score(
    yb_test,
    pred_base
)

baseline_kappa = cohen_kappa_score(
    yb_test,
    pred_base
)

print("Baseline OA =", baseline_oa)
print("Baseline Kappa =", baseline_kappa)

Baseline OA = 0.898
Baseline Kappa = 0.847

In [46]:
active_oa = accuracy_score(
    y_test,
    pred_active
)

active_kappa = cohen_kappa_score(
    y_test,
    pred_active
)

print("Active OA =", active_oa)
print("Active Kappa =", active_kappa)

Active OA = 0.9057777777777778
Active Kappa = 0.8586910974058263

In [12]:
wuhan_human = {
1:2,2:2,3:2,4:2,5:2,
6:1,7:2,8:2,9:2,10:2,
11:2,12:1,13:1,14:2,15:2,
16:2,17:2,18:2,19:1,20:2,

21:1,22:2,23:2,24:2,25:2,
26:2,27:2,28:1,29:2,30:2,
31:1,32:2,33:2,34:2,35:2,
36:1,37:2,38:2,39:2,40:2,

41:2,42:2,43:2,44:2,45:2,
46:2,47:2,48:2,49:2,50:2,
51:2,52:2,53:2,54:2,55:2,
56:2,57:2,58:2,59:2,60:3,

61:2,62:2,63:2,64:2,65:2,
66:2,67:3,68:2,69:2,70:2,
71:2,72:2,73:1,74:2,75:2,
76:2,77:2,78:1,79:2,80:2,

81:2,82:2,83:2,84:2,85:2,
86:2,87:2,88:3,89:3,90:2,
91:3,92:3,93:2,94:2,95:3,
96:2,97:3,98:3,99:2,100:2
}

In [13]:
top100 = pd.read_csv(
    "../data/Wuhan_top100.csv"
)

top100 = top100.reset_index(drop=True)

top100["PointID"] = range(
    1,
    len(top100)+1
)

top100["Human_Class"] = (
    top100["PointID"]
    .map(wuhan_human)
)

top100.head()

          lon        lat  Class  margin  PointID  Human_Class
0  113.968407  30.331121      2     0.0        1            2
1  113.877587  30.361754      2     0.0        2            2
2  114.284344  30.297884      1     0.0        3            2
3  113.961490  30.312796      2     0.0        4            2
4  114.272486  30.983927      1     0.0        5            2

In [14]:
from sklearn.metrics import (
    accuracy_score,
    confusion_matrix,
    classification_report
)

y_true = top100["Human_Class"]

y_pred = top100["Class"]

oa = accuracy_score(
    y_true,
    y_pred
)

print(
    "Wuhan Top100 Accuracy =",
    oa
)

print(
    confusion_matrix(
        y_true,
        y_pred
    )
)

print(
    classification_report(
        y_true,
        y_pred
    )
)

Wuhan Top100 Accuracy = 0.43
[[ 5  3  2]
 [34 36 11]
 [ 4  3  2]]
              precision    recall  f1-score   support

           1       0.12      0.50      0.19        10
           2       0.86      0.44      0.59        81
           3       0.13      0.22      0.17         9

    accuracy                           0.43       100
   macro avg       0.37      0.39      0.31       100
weighted avg       0.72      0.43      0.51       100

In [15]:
top100["Correct"] = (
    top100["Class"]
    ==
    top100["Human_Class"]
)

print(
    top100["Correct"]
    .value_counts()
)

Correct
False    57
True     43
Name: count, dtype: int64